Добавляет докер для быстрой проверки статьи на сайте
Y-Doka/content pull request #1
Opened 2021-03-05 06:58 UTC by nlopin

## Идея

Этот репозиторий — основной для авторов и редакторов статей. Нужно дать им возможность быстро посмотреть, как статья будет выглядеть в проде.

## Решение

[🎥 Демонстрация](https://www.loom.com/share/8770e1fd62014f47843892451f9747b9)

1. Каждое слияние в мастер репы `platform` запускает сборку докер образа и его публикациюю (встроенная фича докер хаба, он умеет за этим следить)
2. Автор делает `docker-compose up` а папке `content`. Скачивается и запускаектся последний образ, к нему монтируется папка с контентом. Запускается локальный сервер
3. Автор правит текст статьи и может вживую наблюдать все изменения

## Анализ

Первый запуск `docker−compose` скачает образ из репозитория. Это 300-400 мб (сейчас 215Мб, но его нужно менять). Время первого запуска будет от минуты до нескольких.

Все последующие запуски будут использовать уже скачанный образ и запуск происходит за секунды.

Если появится новая версия образа, то она обновится автоматически и мы проделаем то де, что и в первом запуске.

2021-03-05 07:01 UTC, furtivite commented
Стоит сразу добавить в папку /docs инструкцию.

2021-03-05 07:25 UTC, furtivite requested changes
Стоит сразу добавить в папку /docs инструкцию.

2021-03-05 22:39 UTC, pepelsbey commented
@furtivite репозитории у нас временные, не стоит ничего в них добавлять на будущее :) Как именно мы переименуем и какие репы создадим — это потом. Сейчас просто отлаживаем взаимодействие двух тестовых реп.

2021-03-07 12:21 UTC, nlopin commented
@pepelsbey а чем они временные? выглядят готовыми для миграции

Я добавлю в корень README.md с описанием разработки, а вы потом подрихтуете. Даже если будем делать новый репозиторий, то просто перенесем туда

2021-03-07 12:24 UTC, pepelsbey commented
Временные потому, ￼что мы пока не решили, как именно мы будем переносить текущую репу: переименовывать или переносить ишью в новые. Я точно делал эти репки временными :)

2021-03-07 13:04 UTC, nlopin commented
@pepelsbey @pepelsbey в любом случае добавил описание

2021-03-09 11:21 UTC, pepelsbey commented on .gitignore
> +
```suggestion
```

Предлагаю проповедовать другой принцип:
1. В документации написать как завести у себя [глобальный .gitignore](https://docs.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer)
2. В игноре проекта будем держать только файлы, которые могут генерироваться проектом

Иначе список может вырасти до бесконечности.

Вот, например мой:

```
$ cat ~/.gitignore
*.pyc
.DS_Store
Desktop.ini
._*
Thumbs.db
.Spotlight-V100
.Trashes
Icon
```

2021-03-09 11:31 UTC, nlopin commented on .gitignore
> +
Мне кажется, что это не проблема, что он вырастет. Стремно, если к нам начнут сыпаться пиары с мусором и за этим нужно следить.

Так не надо будет ничего рассказывать в документации, у нас ее и так много

2021-03-09 19:59 UTC, nlopin commented on .gitignore
> +
Дописывание приветствую

2021-03-09 21:29 UTC, merged