Переносит статью про Node.js
Y-Doka/content pull request #10
Opened 2021-03-12 14:21 UTC by furtivite

- Переносит статью про Node.js
- Правит спеллер

2021-03-14 10:58 UTC, nlopin commented on tools/long/nodejs/index.md
> +- вспомогательные инструменты для клиентских приложений — системы сборки <!--TODO: Ссылку на системы сборки-->, распространения пакетов <!--TODO: Ссылку на менеджеры пакетов-->, серверы разработки, р
тудушки тут были или ты проставил? все эти статьи уже есть, давай проставим ссылки. Думаю ок, что они будут битыми поначалу

2021-03-14 11:02 UTC, furtivite commented on tools/long/nodejs/index.md
> +- вспомогательные инструменты для клиентских приложений — системы сборки <!--TODO: Ссылку на системы сборки-->, распространения пакетов <!--TODO: Ссылку на менеджеры пакетов-->, серверы разработки, р
Я тудушки специально поставил, будет отдельный PR на замену сразу всех ссылок.

2021-03-14 12:52 UTC, nlopin commented on tools/long/nodejs/index.md
> +- вспомогательные инструменты для клиентских приложений — системы сборки <!--TODO: Ссылку на системы сборки-->, распространения пакетов <!--TODO: Ссылку на менеджеры пакетов-->, серверы разработки, р
а зачем? в чем проблема поставить их сразу и не возвращаться к материалу?

2021-03-14 12:56 UTC, furtivite commented on tools/long/nodejs/index.md
> +- вспомогательные инструменты для клиентских приложений — системы сборки <!--TODO: Ссылку на системы сборки-->, распространения пакетов <!--TODO: Ссылку на менеджеры пакетов-->, серверы разработки, р
Хочу поставить такие относительные ссылки, чтобы по ним можно было перейти, независимо от того, ты в собранной платформе или только в контенте, для этого я думаю, что стоит перетащить всё, а дальше проставить ссылки попробовать, чтобы наверняка.

2021-03-15 10:49 UTC, pepelsbey requested changes
Давай мы всё-такие не будем трогать контент во время переноса. Только отрезать «В работе» и править пути к демкам и картинкам.

2021-03-15 12:01 UTC, pepelsbey approved these changes

2021-03-15 12:01 UTC, merged