Переносит статью «Асинхронность в js»
Y-Doka/content pull request #12
Opened 2021-03-13 23:07 UTC by nlopin

2021-03-13 23:07 UTC, nlopin commented on .yaspeller.json
> +    "Робертса"
очень странно, но спеллер не сумел фамилию просклонять

2021-03-13 23:08 UTC, nlopin commented on js/long/async-in-js/practice/bespoyasov.md
> +#### 🛠️ «Отложить выполнение»
тут сохранил уровень заголовков

2021-03-14 11:04 UTC, furtivite requested changes

2021-03-14 11:04 UTC, furtivite commented on .yaspeller.json
> +    "Робертса"
```suggestion
    "Робертс(а|у|ом|)"
```

Может сразу сделать все варианты на случай, если фамилия всплывёт ещё раз?

2021-03-14 11:04 UTC, furtivite commented on .yaspeller.json
> +    "Робертса"
Плюс, может рассортируем по алфавиту?

2021-03-15 08:31 UTC, nlopin commented on .yaspeller.json
> +    "Робертса"
он знает другие варианты, но не показывает именно этот.

По алфавиту по мне так не имеет смысла сортировать, мы же не будем читать этот массив

2021-03-15 08:36 UTC, furtivite commented on .yaspeller.json
> +    "Робертса"
> он знает другие варианты, но не показывает именно этот.

Я проверил, не знает. Может всё же добавим? Только вот так:

`"Робертс(а|е|у|ом|)"`

2021-03-15 08:53 UTC, furtivite approved these changes

2021-03-15 11:11 UTC, pepelsbey requested changes

2021-03-15 11:11 UTC, pepelsbey commented on .yaspeller.json
> +    "Робертс(а|у|ом|)"
```suggestion
    "Робертса"
```
Предлагаю расширять исключения по прецедентам. То есть если нужно слово и его форма — добавляем. Если словарь справляется — не добавляем. Иначе нам нужно перечислить все склонения. В этой статье нет вариантов, кроме `Робертса`, такой вариант и идёт в словарь.

2021-03-15 11:14 UTC, pepelsbey commented on .yaspeller.json
> +    "Робертс(а|у|ом|)"
Есть опыт словаря и подкаста Веб-стандартов — действительно проще наращивать, чем тратить время на все возможные вариации. Итеративно :)

2021-03-15 11:47 UTC, pepelsbey approved these changes

2021-03-15 11:52 UTC, merged