Добавляет доку про глобальные ключевые слова
Y-Doka/content pull request #322
Opened 2021-04-06 18:18 UTC by solarrust

2021-04-06 21:17 UTC, pepelsbey requested changes

2021-04-06 21:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Будьте бдительны! Браузерные стили и значения свойств по умолчанию — не одно и тоже. Сверяйтесь с документацией!
Очень хороший призыв сверяться с источниками, но непонятно, что такое «документация». Куда идти? Я бы развернул: за браузерными стилями туда, за спекой сюда.

2021-04-06 21:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Значения ненаследуемых свойств применяются исключительно для того элемента, которому прописаны. И на детей не распространяются.
Хочется пример ненаследуемого, по аналогии. Самый простой: `background-color`. И я бы ещё объяснил причину, по которой одни свойства наследуются, а другие нет. Что-то очень простое в духе «для одних свуойств это привычно и полезно, для других — нет».

2021-04-06 21:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Это ключевое слово ведёт себя по разному с наследуемыми и ненаследуемыми свойствами.
```suggestion
Это ключевое слово ведёт себя по-разному с наследуемыми и ненаследуемыми свойствами.
```

2021-04-06 21:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
```suggestion
Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(TODO). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
```
Может будем писать TODO? Так проще ищется и есть традиция.

2021-04-06 21:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +
```suggestion
```

2021-04-06 22:03 UTC, solarrust commented on css/doka/global-keywords/index.md
> +Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
На сколько такая запись в тексте будет понятна читателю?

2021-04-07 00:17 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
Если мы говорим про читателя, то оба варианта не очень. В твоём случае это будет битая ссылка:

```html
<a href="в работе"><code>all</code></a>
```

В моём — тоже (

2021-04-07 00:21 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
В обоих случаях получится битая ссылка. Тут кажется нужно решить, что мы в принципе делаем с таким. Была идея делать страницы-плейсхолдеры. Принцип такой: хочешь сослаться куда-то, чего пока нет? Сделай эту страницу из шаблона «Статьи пока нет». В шаблоне пришедший будет приглашаться написать статью.

Обсудим, короче :)

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +Каждое из этих слов выполняет свою функцию, но всех их объединяет то, что любые заданные до этого значения конкретного свойства будут сброшены.
```suggestion
Каждое из этих слов выполняет свою функцию, но все их объединяет то, что любые заданные до этого значения конкретного свойства будут сброшены.
```

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +Например, у свойства `font-style` значение по умолчанию `normal`. Предположим, у нас есть текст, завёрнутый в `<em>`. Браузер отображает текст внутри этого тега курсивом. Обернём последнее предложени
```suggestion
Например, у свойства `font-style` значение по умолчанию `normal`. Предположим, у нас есть текст, завёрнутый в `<em>`. Браузер отображает текст внутри этого тега курсивом. Обернём последнее предложение в `<span>`. По правилам текст последнего предложения тоже будет отображаться курсивом, поскольку свойство `font-style` является наследуемым. Но мы изменим это, задав для селектора `span` значение `font-style: initial`.
```

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +В итоге конкретно для последнего предложения текста, завёрнутого в `<span>`, будет действовать значение `normal` и текст будет отображён в нормальном начертании.
```suggestion
В итоге конкретно для последнего предложения текста, завёрнутого в `<span>`, будет действовать значение `normal`, и текст будет отображён в нормальном начертании.
```

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +Ключевое слово `inherit` позволяет явно задать наследуемость какого-то из свойств, не важно является ли оно наследуемым или нет.
```suggestion
Ключевое слово `inherit` позволяет явно задать наследуемость какого-то из свойств, неважно, является ли оно наследуемым или нет.
```

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +Для примера возьмём абзац текста с вложенным `<span>`. Зададим для `<p>` свойство `border`. Само по себе оно является ненаследуемым, а значит вокруг вложенного в абзац `<span>` своей рамки не будет.
```suggestion
Для примера возьмём абзац текста с вложенным `<span>`. Зададим для `<p>` свойство `border`. Само по себе оно является ненаследуемым, а значит, вокруг вложенного в абзац `<span>` своей рамки не будет.
```

2021-04-07 12:48 UTC, tachisis commented on css/doka/global-keywords/index.md
> +Ключевое слово `inherit` прекрасно работает и для наследуемых свойств. Все указанные для селектора значения свойства сбрасываются и наследуется то значение, которое задано родителю этого элемента.
```suggestion
Ключевое слово `inherit` прекрасно работает и для наследуемых свойств. Все указанные для селектора значения свойства сбрасываются, и наследуется то значение, которое задано родителю этого элемента.
```

2021-04-08 13:11 UTC, solarrust commented on css/doka/global-keywords/index.md
> +Будьте бдительны! Браузерные стили и значения свойств по умолчанию — не одно и тоже. Сверяйтесь с документацией!
Дописала

2021-04-08 13:12 UTC, solarrust commented on css/doka/global-keywords/index.md
> +Значения ненаследуемых свойств применяются исключительно для того элемента, которому прописаны. И на детей не распространяются.
Дописала

2021-04-08 22:51 UTC, pepelsbey requested changes

2021-04-08 22:51 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +С ненаследуемыми свойствами оно ведёт себя как `initial`.
```suggestion
Это ключевое слово ведёт себя по-разному с наследуемыми и ненаследуемыми свойствами:

- С наследуемыми свойствами ключевое слово `unset` ведёт себя как `inherit`.
- С ненаследуемыми свойствами оно ведёт себя как `initial`.
```

Очень просится такая организация, а то строки выглядят сиротливо по-отдельности.

2021-04-08 22:51 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +![Блок с вложенным списком, каждый элемент обведён рамкой](images/inherited-border.jpg)
Неожиданный выбор формата, может PNG? Меньше сжатия — чётче рамки :)

2021-04-08 22:51 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all)(в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
```suggestion
Ключевое слово `unset` очень удобно использовать в качестве значения свойства [`all`](/css/doka/all) (в работе). В этому случае оно само определит тип свойства и _притворится_ нужным значением.
```
Не удалим, так отобьём пробелом

2021-04-09 06:48 UTC, solarrust commented on css/doka/global-keywords/index.md
> +![Блок с вложенным списком, каждый элемент обведён рамкой](images/inherited-border.jpg)
Это автоматическая скриншотилка =) Так ли принципиален формат для микро-картинки?

2021-04-09 07:32 UTC, tachisis approved these changes

2021-04-09 11:03 UTC, pepelsbey commented on css/doka/global-keywords/index.md
> +![Блок с вложенным списком, каждый элемент обведён рамкой](images/inherited-border.jpg)
Хочется показывать лёгкую качественную графику, в Chrome или Firefox можно быстро снять скриншот блока из DevTools в PNG.

2021-04-09 11:16 UTC, solarrust commented on css/doka/global-keywords/index.md
> +![Блок с вложенным списком, каждый элемент обведён рамкой](images/inherited-border.jpg)
done

2021-04-09 11:34 UTC, pepelsbey approved these changes
Спасибо :)

2021-04-09 12:54 UTC, merged