Переносит статью про поток документа
Y-Doka/content pull request #326
Opened 2021-04-07 16:11 UTC by solarrust

2021-04-08 22:43 UTC, pepelsbey requested changes

2021-04-08 22:43 UTC, pepelsbey commented on html/doka/flow/index.md
> +В рамках блочного контекста форматирования вертикальные расстояния между блоками задаются CSS-свойством [`margin`](/css/doka/margin). Если блоку задан нижний отступ, а следующему за ним — верхний, то
```suggestion
В рамках блочного контекста форматирования вертикальные расстояния между блоками задаются CSS-свойством [`margin`](/css/doka/margin). Если блоку задан нижний отступ, а следующему за ним — верхний, то можно ожидать, что итоговый отступ между блоками будет равен сумме этих двух отступов. Но в соответствии со спецификацией соприкасающиеся отступы «схлопываются». То есть, как бы проваливаются один в другой. Итоговый отступ будет равен бо́льшему отступу из двух.
```

Ударение ставится иначе: после гласной добавляется [знак ударения](https://ru.wikipedia.org/wiki/Знак_ударения).

2021-04-08 22:43 UTC, pepelsbey commented on .yaspeller.json
> +    "бóльшему",
```suggestion
```
В таком случае слово-гибрид не нужно.

2021-04-09 06:50 UTC, solarrust commented on html/doka/flow/index.md
> +В рамках блочного контекста форматирования вертикальные расстояния между блоками задаются CSS-свойством [`margin`](/css/doka/margin). Если блоку задан нижний отступ, а следующему за ним — верхний, то
Ставлю ударение Бирмановской раскладкой.

2021-04-09 11:06 UTC, pepelsbey approved these changes

2021-04-09 11:06 UTC, merged