Удаляет блок соавторов, объединяет его с контрибуторами
Y-Doka/content pull request #351
Opened 2021-04-20 07:32 UTC by furtivite

Было:

```markdown
- author: username
- co-authors:
    - username
    - username
- contributors:
    - username
    - username
```

Стало

```markdown
- author: 
    - username
- contributors:
    - username
    - username
    - username
    - username
```

2021-04-20 08:19 UTC, tachisis approved these changes

2021-04-20 09:16 UTC, pepelsbey requested changes
Меня не хватило посмотреть 276 файлов, но в том, что хватило — двойной пробел :)

Плюс заведу задачу про дальнейшую нормализацию, чтобы не усложнять ПР.

2021-04-20 09:16 UTC, pepelsbey commented on css/doka/disabled-enabled/index.md
> +  -  solarrust
```suggestion
  - solarrust
```

Здесь и дальше

2021-04-20 09:23 UTC, furtivite commented on css/doka/disabled-enabled/index.md
> +  -  solarrust
Поправил, больше двойных пробелов нет.

2021-04-20 09:24 UTC, pepelsbey approved these changes

2021-04-23 08:05 UTC, solarrust approved these changes

2021-04-23 08:06 UTC, nlopin approved these changes

2021-04-23 10:44 UTC, merged