Добавляет статью про CSS-анимации
Y-Doka/content pull request #353
Opened 2021-04-20 10:44 UTC by solarrust

2021-04-20 13:32 UTC, pepelsbey requested changes
Это достойно называться лонгридом :) 

Всё круто, но нам бы договориться, что глобальные значения `initial` и `inherit`, которые есть у каждого свойства, мы не указываем среди специфичных.

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +- `inherit` — наследует значение от родительского элемента.
Это неспецифичные для этого свойства значения, которые можно задать всем CSS-свойствам, мне кажется пользы в их перечислении особо нет. Я бы лучше сказал, мол, анимацию можно отменить при наведении, если указать `none` для имени.

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +Теперь анимация проигрывается постоянно, но вы наверняка видите, что после последнего кадра происходит резкий скачёк к исходному состоянию. Выглядит откровенно так себе.
```suggestion
Теперь анимация проигрывается постоянно, но вы наверняка видите, что после последнего кадра происходит резкий скачок к исходному состоянию. Выглядит откровенно так себе.
```

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +- `inherit` — наследует значение от родительского элемента.
См. комментарий выше.

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +Тот же мячик начинает своё движение медленно и со временем ускоряется.
```suggestion
CSS-анимации по умолчанию проигрываются линейно, меняя свойства элемента на равные доли в равные промежутки времени. Такое поведение редко встречается в реальной жизни. Тот же мячик начинает своё движение медленно и со временем ускоряется.
```

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +Задавая значения `x2` и `x4` меньше 0 или больше 1 можно добиться эффекта пружины.
```suggestion
Функция, позволяющая вручную установить любую временную функцию со сложными законами. Значения `x1` и `x3` должны находится в диапазоне от 0 до 1 включительно. Задавая значения `x2` и `x4` меньше 0 или больше 1 можно добиться эффекта пружины.
```

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +Функция, указывающая, что анимация должна воспроизводится _ступеньками_, рвано, резко переходя от одного состояния к другому.
Я бы лучше сказал «шагами» или «пошагово», это лучше подходит изначальному значению.

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +- `inherit` — наследует значение от родительского элемента.
См. выше.

2021-04-20 13:32 UTC, pepelsbey commented on css/articles/animation/index.md
> +      color-change 1s 3 reverse linear;
```suggestion
    circle-to-square 2s infinite alternate-reverse ease-in 1s,
    color-change 1s 3 reverse linear;
```

2021-04-21 08:48 UTC, pepelsbey approved these changes

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +В процессе развития веб из текста с картинками превратился в интерактивное пространство. Заходя на разные сайты, вы постоянно видите анимации. От микроскопических реакций на наведение курсора, до сло
```suggestion
Веб в процессе развития из текста с картинками превратился в интерактивное пространство. Заходя на разные сайты, вы постоянно видите анимации. От микроскопических реакций на наведение курсора до сложных сцен.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Чтобы рассказать браузеру с чего начать и чем закончить анимацию используется директива `@keyframes`.
```suggestion
Чтобы рассказать браузеру, с чего начать и чем закончить анимацию, используется директива `@keyframes`.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Представим что у нас есть два блока: красный круг и синий квадрат. Мы хотим написать анимацию так, чтобы красный круг превращался в синий квадрат, а синий квадрат превращался в красный круг.
```suggestion
Представим, что у нас есть два блока: красный круг и синий квадрат. Мы хотим написать анимацию так, чтобы красный круг превращался в синий квадрат, а синий квадрат превращался в красный круг.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Начать создание нашей анимации нужно с разложения её на шаги —_ключевые кадры_. Наша анимация будет простая, у неё будет всего 2 ключевых кадра.
```suggestion
Начать создание нашей анимации нужно с разложения её на шаги — _ключевые кадры_. Наша анимация будет простая, у неё будет всего два ключевых кадра.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Чтобы превратить красный круг в синий квадрат нам нужно будет поменять два свойства: [`border-radius`](/css/doka/border-radius) и [`background-color`](/css/doka/background-color).
```suggestion
Чтобы превратить красный круг в синий квадрат, нам нужно будет поменять два свойства: [`border-radius`](/css/doka/border-radius) и [`background-color`](/css/doka/background-color).
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Чтобы прописать ключевые кадры используем директиву `@keyframes`:
```suggestion
Чтобы прописать ключевые кадры, используем директиву `@keyframes`:
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Чтобы анимация начала проигрываться нам нужно присвоить её какому-то элементу, чтобы браузер понимал, какой элемент на странице анимировать.
```suggestion
Чтобы анимация начала проигрываться, нам нужно присвоить её какому-то элементу, чтобы браузер понимал, какой элемент на странице анимировать.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +  animation: some-animation 2s;
```suggestion
  animation: some-animation;
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +  animation: some-animation 2s;
Потому что это спойлер, мы только потом рассказываем про тайминг

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +При помощи свойства `animation-duration` пропишем длительность одного цикла анимации. Значением этого свойства указывается в секундах `s` или миллисекундах `ms`.
```suggestion
При помощи свойства `animation-duration` пропишем длительность одного цикла анимации. Значение этого свойства указывается в секундах `s` или миллисекундах `ms`.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +При помощи свойства `animation-iteration-count` можно указать сколько раз анимация будет проигрываться.
```suggestion
При помощи свойства `animation-iteration-count` можно указать, сколько раз анимация будет проигрываться.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +В качестве значение указывается число, означающее количество повторений или ключевое слово `infinite`. Если указано `infinite`, то анимация будет повторяться бесконечно. Это значение встречается чаще
```suggestion
В качестве значения указывается число, означающее количество повторений, или ключевое слово `infinite`. Если указано `infinite`, то анимация будет повторяться бесконечно. Это значение встречается чаще всего!
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Анимации пришли в веб в попытке стереть границу между реальным миром и компьютером. В реальном мире вещи не меняют свои свойства мгновенно. Мячик перемещается из вашей руки на пол не моментально, а п
```suggestion
Анимации пришли в веб в попытке стереть границу между реальным миром и компьютерным. В реальном мире вещи не меняют свои свойства мгновенно. Мячик перемещается из вашей руки на пол не моментально, а плавно меняя свою позицию в пространстве.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +При помощи свойства `animation-timing-function` можно задать как будет развиваться анимация между ключевыми кадрами: равномерно; сначала быстро, потом медленно; по каким-то сложным внутренним законам
```suggestion
При помощи свойства `animation-timing-function` можно задать, как будет развиваться анимация между ключевыми кадрами: равномерно, или сначала быстро, потом медленно, или по каким-то сложным внутренним законам.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Анимация начинается медленно, разгоняется быстро и снова замедляется к концу.
```suggestion
Анимация начинается медленно, затем быстро разгоняется и снова замедляется к концу.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Функция, позволяющая вручную установить любую временную функцию со сложными законами. Значения `x1` и `x3` должны находится в диапазоне от 0 до 1 включительно. Задавая значения `x2` и `x4` меньше 0 и
Мне не очень нравится «функция, позволяющая установить функцию», но я не очень в математике. Можно ли подобрать синоним одному из употреблений?

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Функция, позволяющая вручную установить любую временную функцию со сложными законами. Значения `x1` и `x3` должны находится в диапазоне от 0 до 1 включительно. Задавая значения `x2` и `x4` меньше 0 и
```suggestion
Функция, позволяющая вручную установить любую временную функцию со сложными законами. Значения `x1` и `x3` должны находиться в диапазоне от `0` до `1` включительно. Задавая значения `x2` и `x4` меньше `0` или больше `1`, можно добиться эффекта пружины.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Редко когда разработчики пишут эту функцию _из головы_. Чаще всего используется инструмент визуализации, позволяющий изменять значения и сразу видеть как будет выглядеть анимация.
```suggestion
Редко когда разработчики пишут эту функцию _из головы_. Чаще всего используется инструмент визуализации, позволяющий изменять значения и сразу видеть, как будет выглядеть анимация.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Один из самых популярных инструментов [cubic-bezier.com](https://cubic-bezier.com/).
```suggestion
Один из самых популярных инструментов — [cubic-bezier.com](https://cubic-bezier.com/).
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Задаёт пошаговую анимацию, разбивая анимацию на отрезки, изменения происходят в начале каждого шага.
```suggestion
Задаёт пошаговую анимацию, разбивая её на отрезки, изменения происходят в начале каждого шага.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Функция, указывающая, что анимация должна воспроизводится _шагами_, резко переходя от одного состояния к другому.
```suggestion
Функция, указывающая, что анимация должна воспроизводиться _шагами_, резко переходя от одного состояния к другому.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Первый параметр указывает на сколько отрезков нужно разбить анимацию. Значением должно быть целое положительное число больше 0.
```suggestion
Первый параметр указывает, на сколько отрезков нужно разбить анимацию. Значением должно быть целое положительное число больше `0`.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +- `jump-none` — все шаги происходят в пределах от 0 до 1 включительно.
```suggestion
- `jump-none` — все шаги происходят в пределах от `0` до `1` включительно.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Очень сложно представить как же будет выглядеть анимация при каждом из этих значений. Гораздо информативнее будет демка:
```suggestion
Очень сложно представить, как же будет выглядеть анимация при каждом из этих значений. Гораздо информативнее будет демка:
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Вернёмся к нашему красному кругу и укажем, что он должен превращаться в синий квадрат не линейно, медленно разгоняясь к концу анимации.
```suggestion
Вернёмся к нашему красному кругу и укажем, что он должен превращаться в синий квадрат нелинейно, медленно разгоняясь к концу анимации.
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Пришло время заняться правой фигурой и превратить синий квадрат в красный круг. Используем практически те же самые свойства, что и для круга, только зададим другое значение для свойства `animation-di
```suggestion
Пришло время заняться правой фигурой и превратить синий квадрат в красный круг. Используем практически те же самые свойства, что и для круга, только зададим другое значение для свойства `animation-direction`, чтобы шаги анимации воспроизводились в обратном порядке:
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Значения указываются через пробел. Порядок указания значений не важен. Из-за того, что значения этих свойств очень разные, браузер сам догадывается какое значение к какому свойству относится. Важно т
```suggestion
Значения указываются через пробел. Порядок указания значений не важен. Из-за того, что значения этих свойств очень разные, браузер сам догадывается, какое значение к какому свойству относится. Важно только помнить, что первое значение времени будет воспринято как значение `animation-duration` (длительность анимации), а второе — `animation-delay` (задержка воспроизведения).
```

2021-04-21 16:58 UTC, tachisis commented on css/articles/animation/index.md
> +Есть возможность применить к одному элементу сразу несколько анимаций. Для этого нужно перечислить несколько значений через запятую. Возможно указать любое количество значений для любого из свойств а
А можно дописать, что при этом будет?

2021-04-21 18:25 UTC, solarrust commented on css/articles/animation/index.md
> +Есть возможность применить к одному элементу сразу несколько анимаций. Для этого нужно перечислить несколько значений через запятую. Возможно указать любое количество значений для любого из свойств а
Дописала и запилила демку

2021-04-21 18:25 UTC, solarrust commented on css/articles/animation/index.md
> +Функция, позволяющая вручную установить любую временную функцию со сложными законами. Значения `x1` и `x3` должны находится в диапазоне от 0 до 1 включительно. Задавая значения `x2` и `x4` меньше 0 и
Переписала и добавила картинку с кривой Безье

2021-04-22 09:58 UTC, tachisis approved these changes

2021-04-22 09:59 UTC, merged

2021-04-22 10:00 UTC, solarrust commented
💃🏻