Создаёт страницу О проекте
Y-Doka/content pull request #354
Opened 2021-04-20 10:48 UTC by furtivite

Вижу проблему в том, что в контентном репозитории хранится информация о лейауте для статики. Но решение этой проблемы — заводить для статики отдельную папку, а потом подменять URLs фильтрами, как это работает сейчас.

2021-04-20 13:13 UTC, pepelsbey requested changes

2021-04-20 13:13 UTC, pepelsbey commented on about/index.md
> +---
```suggestion
---
title: "Что такое Дока"
layout: base.njk
---
```

2021-04-20 13:13 UTC, pepelsbey commented on about/index.md
> +- Создать тестирование, которое позволит оценить уровень веб-разработки и найти пробелы
```suggestion
```

Мне кажется, что это слишком уж внутренние планы и стоит задуматься, как мы будем выглядеть при запуске. Именно запуск будет нашей нулевой точкой для публики.

2021-04-20 13:39 UTC, furtivite commented on about/index.md
> +- Создать тестирование, которое позволит оценить уровень веб-разработки и найти пробелы
Можно вообще убрать, мы с @anurodov эту штуку обсуждали при самом первом запуске. Пока можно убрать этот блок.

2021-04-20 13:42 UTC, furtivite commented on about/index.md
> +---
Тут не `base.njk`, а именно `page.njk`, отличия в наличии `{{ title }}` и `footer` - `base.njk` — это обычная обёртка.

2021-04-20 13:50 UTC, pepelsbey commented on about/index.md
> +---
Ок, не заметил

2021-04-20 18:42 UTC, pepelsbey approved these changes

2021-04-21 12:11 UTC, tachisis approved these changes

2021-04-21 12:13 UTC, merged