Добавляет статью про !important
Y-Doka/content pull request #384
Opened 2021-04-29 13:31 UTC by solarrust

Закрывает https://github.com/Y-Doka/y-doka.site/issues/405

2021-04-29 22:01 UTC, pepelsbey requested changes
Я добавил себе задачу [написать про всякие штучки из опыта](https://github.com/Y-Doka/content/issues/386), но мне кажется в базовой статье не хватает важной мысли: а зачем вообще использовать `!important`, если его использовать нельзя? Нужно как-то намекнуть на полезные случаи: легаси, расширения, пользовательские стили.

2021-05-03 10:32 UTC, solarrust commented
@pepelsbey дописала варианты использования

2021-05-04 10:47 UTC, pepelsbey commented on css/doka/important/index.md
> +Если вы работаете с проектом, в котором большая и старая кодовая база. И, предположим, у вас нет доступа к редактированию старых стилей. Вы пишите новый файл со стилями, но часть из них конфликтует с
```suggestion
Если вы работаете с проектом, в котором большая и старая кодовая база, то бывает опасно править эти стили — кто знает, что может посыпаться. Поэтому в таких ситуациях новые стили дописывают, чтобы переопределить старые, а если не хватает специфичности — добавляют `!important`.
```
Повернул объяснение иначе: не про доступ к правке, а к опасности таких правок.

2021-05-04 10:47 UTC, pepelsbey commented on css/doka/important/index.md
> +Если есть какие-то стили, которые критически важны для сайта, если их изменение всё разрушит, то будет логично сделать их _железобетонными_ — дополнить правила модификатором `!important`.
Я проверил: кажется в браузерах уже не осталось встроенных способов подключать пользовательские стили. Поэтому ситуация с железобетонными стилями кажется скорее несуществующая на практике. Обычно наоборот: в пользовательских стилях пишут `!important`, поскольку [по каскаду](https://drafts.csswg.org/css-cascade-5/#cascade-origin) они раньше, чем стили сайта. И если в пользовательских написать `!important`, то их из авторских уже не перебить.

Короче, я бы скорее убрал эту часть, она экзотическая.

2021-05-04 10:58 UTC, solarrust commented on css/doka/important/index.md
> +Если есть какие-то стили, которые критически важны для сайта, если их изменение всё разрушит, то будет логично сделать их _железобетонными_ — дополнить правила модификатором `!important`.
Удалила

2021-05-04 20:34 UTC, pepelsbey approved these changes

2021-05-04 20:36 UTC, merged

2021-05-04 20:39 UTC, pepelsbey commented
@tachisis посмотришь уже отдельным делом?