Рефакторит статью про <img>
Y-Doka/content pull request #494
Opened 2021-05-03 10:09 UTC by solarrust

Начало тут https://github.com/Y-Doka/y-doka.site/pull/621

2021-05-05 14:41 UTC, pepelsbey commented
Сильно [подрефакторил](https://github.com/Y-Doka/content/pull/494/commits/2db40450aa039f880d7fc99f9cd2fe5ce1ec7ff4) статью:

- Расписал подробнее про атрибут `alt`
- Разделил описание `srcset` и `sizes` по сценариям использования
- Добавил новый атрибут `loading`
- Сделал демку полезнее: указал атрибуты, объяснил про адаптивность.

2021-05-05 16:38 UTC, pepelsbey approved these changes

2021-05-06 10:37 UTC, solarrust commented
@tachisis и сюда загляни =)

2021-05-11 18:40 UTC, tachisis requested changes
Немного правочек

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +  - pepelsbey
```suggestion
  - pepelsbey
editor: tachisis
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +<img src="logo.png" alt="Логотип, собака, бегущая за мячом, изображено схематично">
```suggestion
<img src="logo.png" alt="Логотип: собака, бегущая за мячом, изображено схематично">
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +Браузер остановит проверку и чтение атрибутов как только найдёт совпадение с условием. Поэтому располагайте условия от меньших к большим.
```suggestion
Браузер остановит проверку и чтение атрибутов, как только найдёт совпадение с условием. Поэтому располагайте условия от меньших к большим.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +Но бывает, что картинок на странице много и нам нужно как-то подсказать браузеру: вот эти пока не грузи, дождись пока пользователь до них прокрутит и можно начать грузить. _В общем, сам разберись._ У
```suggestion
Но бывает, что картинок на странице много, и нам нужно как-то подсказать браузеру: вот эти пока не загружай, дождись, пока пользователь до них прокрутит — и можно начать загрузку. _В общем, сам разберись._ Удобно, правда?
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +- `eager`, то есть рьяно (по умолчанию, как если вообще не указывать атрибут);
```suggestion
- `eager`, то есть немедленно (по умолчанию, как если вообще не указывать атрибут);
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +Атрибут сравнительно свежий и стоит свериться с [таблицей поддержки](https://caniuse.com/loading-lazy-attr), но это не так важно: атрибут `loading` работает как улучшение и если браузер его не поддер
```suggestion
Атрибут сравнительно свежий, и стоит свериться с [таблицей поддержки](https://caniuse.com/loading-lazy-attr), но это не так важно: атрибут `loading` работает как улучшение, и если браузер его не поддерживает, то ничего не сломается.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +💡 Всегда прописывайте `alt` для изображения. Если пользователь открывает страницу в скринридере браузере, или он отключил изображения, или использует озвучивание текста с экрана, то альтернативный те
```suggestion
💡 Всегда прописывайте `alt` для изображения. Если пользователь открывает страницу в скринридере, или он отключил изображения, или использует озвучивание текста с экрана, то альтернативный текст подскажет, что изображено на картинке.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
>  💡 Прописывай ширину `width` и высоту `height` изображения, чтобы страница загружалась быстрее. Задавая значения этим атрибутам не пишите `px`, только числа.
```suggestion
💡 Прописывайте ширину `width` и высоту `height` изображения, чтобы страница загружалась быстрее. Задавая значения этим атрибутам, не пишите `px`, только числа.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
>  💡 Используй атрибуты `sizes` и `srcset`, чтобы ваша картинка адаптировалась на разных устройствах. Получается красиво, а страница загружается быстрее.
```suggestion
💡 Используйте атрибуты `sizes` и `srcset`, чтобы ваша картинка адаптировалась на разных устройствах. Получается красиво, а страница загружается быстрее.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/index.md
> +  alt="Три собаки: одна смотрит влево, вторая закрыла глаза и спит, третья смотрит вправо.">
```suggestion
  alt="Три собаки: одна смотрит влево, вторая закрыла глаза и спит, третья смотрит вправо">
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/practice/solarrust.md
> +Поэтому прежде чем каким-либо образом изменять изображение задай для `<img>` свойство `display` со значением `block` или `inline-block`.
```suggestion
Поэтому прежде чем как-то изменять изображение, задай для `<img>` свойство `display` со значением `block` или `inline-block`.
```

2021-05-11 18:40 UTC, tachisis commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
Имеется в виду Mac с ретиной? Наверное, стоит уточнить.

2021-05-12 08:00 UTC, solarrust commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
```suggestion
🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком разрешении и откроется. Но на Mac с ретина экраном та же картинка будет выглядеть размыто, потому что на ретине по умолчанию использует разрешение в два раза больше — 144dpi. Поэтому ты можешь указать, например, для больших экранов 2k или 4k более крупную картинку. Или даже вертикальную картинку для отображения на мобильных, чтобы она красивее отображалась и не обрезалась. Всё это надо указывать именно в `<img>`.
```

2021-05-12 08:00 UTC, solarrust commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
@tachisis так норм?

2021-05-12 08:27 UTC, tachisis commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
@solarrust я капельку отредактировала прямо твой suggestion, так будет норм, спасибо!

2021-05-12 08:28 UTC, tachisis approved these changes
Последняя правочка выше — и можно мержить!

2021-05-12 08:45 UTC, pepelsbey commented on html/doka/img/practice/solarrust.md
> +Поэтому прежде чем как-то изменять изображение, задай для `<img>` свойство `display` со значением `block` или `inline-block`.
Только заметил совет, есть вопрос: псевдоэлементы, насколько я понимаю, в принципе не работают на замещённых элементах типа `<img>`, даже если добавить `display: block` или `inline-block`. Так что совет не очень понятен.

2021-05-12 08:50 UTC, pepelsbey commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
Мне кажется совет в принципе сомнительный.

> на обычном Windows-экране
> разрешение в два раза больше — 144dpi

Не бывает Windows-экранов: бывают обычные и ретиновые, или HiDPI. Есть куча устройств на Windows, где двукратная плотность пикселей. Ну и плотность измеряется в ppi (pixel per inch), которая очень отличается от устройства к устройству.

Я бы удалил или сильно переписал совет, у нас в теле статьи достаточно информации про `srcset` для ретиновых картинок.

2021-05-12 08:51 UTC, pepelsbey requested changes
Есть проблемки с советами, только заметил.

2021-05-12 08:59 UTC, solarrust commented on html/doka/img/practice/solarrust.md
> +Поэтому прежде чем как-то изменять изображение, задай для `<img>` свойство `display` со значением `block` или `inline-block`.
Ты прав, странный совет получился. Перепишу

2021-05-13 09:02 UTC, solarrust commented on html/doka/img/practice/vladimir.md
>  🛠 Очень важен атрибут `srcset`: в нём прописываются варианты картинки для других экранов. Допустим, если ты на обычном Windows-экране откроешь картинку с разрешением 72dpi, она по умолчанию в таком р
Удалила совет

2021-05-13 09:02 UTC, solarrust commented on html/doka/img/practice/solarrust.md
> +Поэтому прежде чем как-то изменять изображение, задай для `<img>` свойство `display` со значением `block` или `inline-block`.
Переписала совет, добавила демку

2021-05-13 16:52 UTC, pepelsbey commented on html/doka/img/practice/solarrust.md
> +  <img class="child" src="some-image.jpg" alt="Abstraction">
```suggestion
  <img class="child" src="some-image.jpg" alt="Какая-то картинка">
```

Лучше по-русски, по мотивам названия файла.

2021-05-15 06:55 UTC, tachisis reviewed
Еще чуточку)

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/demos/img-fix-width.html
> +  <img src="../images/dogs.png" width="1504" height="541" alt="Три собаки: одна смотрит влево, вторая закрыла глаза и спит, третья смотрит вправо.">
```suggestion
  <img src="../images/dogs.png" width="1504" height="541" alt="Три собаки: одна смотрит влево, вторая закрыла глаза и спит, третья смотрит вправо">
```

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/index.md
> +💡 Используйте атрибуты `sizes` и `srcset`, чтобы ваша картинка адаптировалась на разных устройствах. Получается красиво, а страница загружается быстрее.
```suggestion
💡 Используйте атрибуты `sizes` и `srcset`, чтобы ваша картинка адаптировалась к разным устройствам. Получается красиво, а страница загружается быстрее.
```

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/index.md
> +Мы указали картинке её реальные размеры в атрибутах `width` и `height`, а потом задали ей резиновую ширину `50%` и чтобы высота была корректной, добавили `height: auto` — браузер сам подберёт подходя
```suggestion
Мы указали картинке её реальные размеры в атрибутах `width` и `height`, а потом задали ей резиновую ширину `50%`, и чтобы высота была корректной, добавили `height: auto` — браузер сам подберёт подходящую высоту, он уже загрузил картинку и всё знает.
```

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/practice/solarrust.md
> +🛠 Частый дизайнерский приём — наложение поверх картинки цветного оверлея. И если для фоновой картинки это можно сделать при помощи псевдоэлемента, то с тегом `<img>` этот приём не сработает. Для этог
```suggestion
🛠 Частый дизайнерский приём — наложение поверх картинки цветного оверлея. И если для фоновой картинки это можно сделать при помощи псевдоэлемента, то с тегом `<img>` этот приём не сработает. Для этого элемента невозможно задать псевдоэлемент, так уж устроены _замещаемые_ элементы, вроде `<iframe>`, `<video>`, `<img>` и других.
```

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/practice/solarrust.md
> +Чтобы реализовать оверлей нужно будет завернуть картинку в дополнительный блок-обёртку и уже ей задать псевдоэлемент.
```suggestion
Чтобы реализовать оверлей, нужно будет завернуть картинку в дополнительный блок-обёртку и уже ей задать псевдоэлемент.
```

2021-05-15 06:55 UTC, tachisis commented on html/doka/img/practice/solarrust.md
> +  <img class="child" src="some-image.jpg" alt="Какая-то картинка">
```suggestion
  <img class="child" src="some-image.jpg" alt="Три собаки: одна смотрит влево, вторая закрыла глаза и спит, третья смотрит вправо">
```

2021-05-15 07:29 UTC, tachisis approved these changes

2021-05-15 07:38 UTC, merged