doka-content: статья по array find
Y-Doka/content pull request #499
Opened 2021-05-05 16:07 UTC by KognitivnayaBuena

2021-05-06 21:27 UTC, nlopin commented on js/doka/array-find/index.md
> +    return true;
согласен, лучше вариант, приближенный к реальности

2021-05-06 21:49 UTC, nlopin requested changes
Классный старт 🔥

Нужна еще демка, как в остальных

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +Метод массива `find` вернет первый найденый в массиве элемент, который подходит по условию в переданной колбэк-функции. Если в массиве не найдется ни оного подходящего элемента, то вернется знаечние
```suggestion
Метод массива `find` вернет первый найденый в массиве элемент, который подходит по условию в переданной колбэк-функции. Если в массиве не найдется ни одного подходящего элемента, то вернется значение undefined.
```

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +Аналогично методу `filter`, метод `find` необходимо передать аргументом функцию. Функция должна возвращать boolean, т.е результатом должен быть `true` или `false`. Главное отличие от функции `filter`
Сейчас всё объяснение строится на предположении, что читатель знает о том, как работает `filter`. Чтобы разобраться, нужно сначала разобраться с `filter`. Давай расскажем о том, как работает `find` без этого  сравнения. 

Сравнить `find` и `filter` нужно, но как дополнение. Например, сделать пример в разделе «Как понять»

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +function predicate(element, index, array) {
может тогда назовём `isEven`?

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +- `arr` — сам массив, который мы перебираем
```suggestion
- `arr` — сам массив, который перебираем
```

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +const checkFunction = (element) => {
давай ее называть так же, как в примере выше. Так читателю будет понятно, что это та же самая функция, что и выше в тексте

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +    return result;
если я не ошибаюсь, то такой код выдаст ошибку, потому что `return` вне функции не имеет смысла

2021-05-06 21:49 UTC, nlopin commented on js/doka/array-find/index.md
> +`find` позволит нам уменьшить код и сделать его более понятным:
```suggestion
`find` позволит писать меньше кода и сделать его более понятным:
```

2021-05-11 22:09 UTC, nlopin commented on js/doka/array-find/index.md
> +От результата выполнения функции зависит, попадёт ли элемент в итоговый массив:
у нас ведь `find` и итогового массива нет, есть только найденный элемент

2021-05-11 22:10 UTC, nlopin commented on js/doka/array-find/index.md
> +// функция-предикат которая проверяет является ли число нечетным
комментарий надо вынести из кода и превратить в вводный текст

2021-05-11 22:11 UTC, nlopin commented on js/doka/array-find/index.md
> +function isEven(element, index, array) {
Почему так сложно? 

Для проверки чётности можно вндь просто смотреть на остаток от деления на 2: `const isEven = (element) => {return element % 2 === 0}`

2021-05-11 22:15 UTC, nlopin commented on js/doka/array-find/index.md
> +Аналогично методу `filter`, метод `find` необходимо передать аргументом функцию. Функция должна возвращать
Давай эту часть отожмём.  Мы уже несколько раз говорили, что нужно передавать в функцию `find`, поэтому я бы говорил только о том, что эти функции аналогичны и не рассказывал подробности. Чтобы читатель мог пойти посмотреть подробности, нужно поставить ссылку на описание `filter`

Разницу ты классно описала

2021-05-11 22:15 UTC, nlopin commented on js/doka/array-find/index.md
> +console.log(result) // [2]
Давай еще рядом напишем `find` и покажем, какой результат у него

2021-05-23 14:31 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +В метод `find` необходимо передать аргументом функцию. Функция должна возвращать boolean, т.е результатом должен быть `true` или `false`. Функция `find` возвращает первый подходящий во условию в функ
поправила

2021-05-23 14:32 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +Чтобы получить необходимый элемент, нужно определить условие поиска. В этом нам поможет функция-предикат. Этот тип функций подразумевает под собой результат булевого значения.
поправила)

2021-05-23 14:34 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +От результата выполнения функции зависит, попадёт ли элемент в итоговый массив:
поправила

2021-05-23 14:56 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +// функция-предикат которая проверяет является ли число нечетным
поправила

2021-05-23 14:56 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +function isEven(element, index, array) {
поправила

2021-05-23 15:15 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +Аналогично методу `filter`, метод `find` необходимо передать аргументом функцию. Функция должна возвращать
поправила

2021-05-23 15:22 UTC, KognitivnayaBuena commented on js/doka/array-find/index.md
> +console.log(result) // [2]
добавила)

2021-05-26 11:10 UTC, nlopin approved these changes
Супер!

2021-05-26 11:15 UTC, merged