Добавляет доку "Что такое файл"
Y-Doka/content pull request #503
Opened 2021-05-06 20:26 UTC by nigsekor

Этот PR относится к #379 .

@nlopin, я не стал делать картинки, кажется они лишние, но не уверен.

2021-05-11 22:02 UTC, nlopin requested changes
Прокомментировал отдельные места, но в целом все хочется отжать и рассказать менее академично. 

Сейчас в тексте много терминов, которые нигде не оговорены (например, «аппаратная реализация»). Давай попробуем их максильно заменить понятными внешнему читателю словами.

Представь, что нужно рассказать про файлы менеджеру проектов или финансисту

2021-05-12 11:57 UTC, nigsekor commented on tools/doka/file/index.md
> +Файл — это набор сгруппированных данных, записанных на физическом носителе информации и имеющих имя для быстрого доступа в операционной системе. Файлы имеют атрибуты, которые определяют поведение опе
Можно и так :)

2021-05-12 11:57 UTC, nigsekor commented on tools/doka/file/index.md
> +Файл — интуитивно понятная абстракция, которая пришла из физического мира. До появления компьютеров файлом называли коробку, папку, шнур, пружину и что-то подобное, с помощью которых можно было собра
Буду надеятся, что тупым он себя не почувствует

2021-05-12 11:58 UTC, nigsekor commented on tools/doka/file/index.md
> +Программа — это набор инструкций для обработки данных. Чтобы программа работала, в оперативную память необходимо поместить эти данные. В первых электронных компьютерах программы (набор инструкций) пе
Хорошо

2021-05-12 12:05 UTC, igsekor commented on tools/doka/file/index.md
> +Программа — это набор инструкций для обработки данных. Чтобы программа работала, в оперативную память необходимо поместить эти данные. В первых электронных компьютерах программы (набор инструкций) пе
Хорошо

2021-05-12 12:08 UTC, igsekor commented on tools/doka/file/index.md
> +Файл — это набор сгруппированных данных, записанных на физическом носителе информации и имеющих имя для быстрого доступа в операционной системе. Файлы имеют атрибуты, которые определяют поведение опе
Можно и так :)

2021-05-12 12:09 UTC, igsekor commented on tools/doka/file/index.md
> +Файл — интуитивно понятная абстракция, которая пришла из физического мира. До появления компьютеров файлом называли коробку, папку, шнур, пружину и что-то подобное, с помощью которых можно было собра
Буду надеятся и делать все, чтобы тупым читатель себя не почувствовал

2021-05-16 20:32 UTC, nlopin requested changes
Много комментариев, но статья мне кажется очень важной.

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/index.md
> +Такая структура позволяет хранить большое количество файлов в разных директориях, в том числе с одинаковым именем, избегая коллизий. Путь до файла в дереве директорий является неотъемлемой частью пол
```suggestion
Такая структура позволяет хранить файлы в разных директориях. Полное имя файла состоит из пути до файла в дереве директорий и имени файла. Таким способом обеспечивается уникальность имён. Файлы с одинаковыми именами не создают коллизии, если хранятся в разных директориях.

Один уровень иерархии от другого отделяется особым символом (например, `/` для Unix-подобных систем и `\` для операционных систем на базе Windows). Поддерживаются и относительные имена файлов, из которых можно сформировать полное имя путём конкатенации (сложения строк) имени директории и относительного имени. 
```

Относительный путь сложно сформилирован, сможем проще?

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/index.md
> +- поддерживаются символические ссылки;
сошлёмся на статью, где мы разбираем симлинки?

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/practice/igsekor.md
> +### Браузер и имена файлов в Интернете
стоит сказать, что относительных путей нет. или есть?

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/practice/igsekor.md
> +Абсолютное имя файла включает в себя букву логического диска, после которой обязательно идёт двоеточие и обратная косая черта (back slash) `:\`. Затем через символ `\` перечисляются все поддиректории
хочется примеров

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/practice/igsekor.md
> +### Запрещённые символы
может стоит эту инфу добавить к подразделы выше? у нас там как раз есть деление на винду и юникс

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/practice/igsekor.md
> +Расширение имени файла часто используется для идентификации формата файла. Это нужно исключительно для интерфейса пользователя и простой фильтрации, сортировки или группировки имён файлов. В операцио
Нужны примеры

2021-05-16 20:32 UTC, nlopin commented on tools/doka/file/index.md
> +title: Что такое файл
Кажется мы рассказали не только про файлы, но и про пути к ним. Предлагаю поменять заголовок статьи

2021-05-17 11:27 UTC, igsekor commented on tools/doka/file/index.md
> +Большинство операционных систем для экономии времени пользователя применяют кэширование и буферизацию. Например, при записи новых данных в файл или при изменении существующих, операционная система по
Ну можно и так.

2021-05-17 11:33 UTC, igsekor commented on tools/doka/file/index.md
> +Коллизии можно разрешать очень простым методом — не позволять создавать файлы с одинаковыми именами. Исторически первой моделью организации файлов была одноуровневая файловая система. Но использовать
```suggestion
Один из методов решения коллизий — запретить создавать файлы с одинаковыми именами.

Первой моделью организации файлов была одноуровневая(может сказать плоская?) файловая система. Использовать такую файловую систему неудобно, если в операционной системе работает несколько пользователей и используется большое количество файлов. Однако одноуровневые файловые системы до сих пор применяются для определённых устройств. Например, в стиральных машинах или в микроволновых печах.

Продолжением одноуровневых файловых систем являются системы с фиксированным количеством уровней. Такие файловые системы используются на маршрутизаторах и телевизорах.
```

2021-05-17 11:34 UTC, igsekor commented on tools/doka/file/index.md
> +Такая структура позволяет хранить большое количество файлов в разных директориях, в том числе с одинаковым именем, избегая коллизий. Путь до файла в дереве директорий является неотъемлемой частью пол
Думаю, сможем

2021-05-17 11:34 UTC, igsekor commented on tools/doka/file/index.md
> +- поддерживаются символические ссылки;
Конечно!

2021-05-17 11:36 UTC, igsekor commented on tools/doka/file/index.md
> +title: Что такое файл
Может так?

```suggestion
title: Файл и файловые системы
```

2021-05-17 11:53 UTC, igsekor commented on tools/doka/file/index.md
> +Изначально под файлом понимали последовательность байтов. Их можно было вводить вручную с помощью специального устройства — телетайпа. С появлением магнитных лент для хранения данных стали использова
Может так?

```suggestion
Данные в компьютере представляется в виде последовательности машинных слов (байтов). Раньше машинные слова в оперативную память компьютера вводили вручную с помощью специального устройства — телетайпа. Вся последовательность находилась в распечатанном или письменном виде и называлась _файлом_.

С появлением магнитных лент для хранения данных стали использовать другую модель — последовательность записей переменной длины. Считать с магнитной ленты данные или записать их на неё можно только последовательно (последовательный доступ). _Файлом_ стали называть часть магнитной ленты с записанными на неё данными. Программисты должны были знать, с какого по какое место на ленте записаны их данные.

Когда появились перфокарты, данные стали разделять на записи постоянной длины, поскольку на одной перфокарте умещалось [определённое количество](https://ru.wikipedia.org/wiki/Перфокарта) машинных слов. _Файлом_ стали называть последовательность перфокарт с нужными данными. Доступ оставался последовательным, но загрузить можно было произвольный файл, отдав компьютеру нужную стопку перфокарт.

Чуть позже были разработаны модели иерархической организации данных в файлах с помощью дерева поиска. Это позволило очень быстро производить поиск по файлу. Эти модели применяются и сейчас, в специализированных системах хранения. Применение иерархических моделей стало возможно, благодаря появлению носителей информации с произвольным доступом.
```

2021-05-17 15:37 UTC, igsekor commented on tools/doka/file/index.md
> +Большинство операционных систем для экономии времени пользователя применяют кэширование и буферизацию. Например, при записи новых данных в файл или при изменении существующих, операционная система по
Добавлю после отработки текста! :)

2021-05-17 15:39 UTC, igsekor commented on tools/doka/file/index.md
> +- файлы — листья дерева.
Сделаем :)

2021-05-17 15:51 UTC, igsekor commented on tools/doka/file/practice/igsekor.md
> +Путь является неотъемлемой частью имени файла. Абсолютным (полным) именем файла называется путь от корневой директории, относительным — путь от текущей (рабочей) директории. В одной директории не мож
```suggestion
Путь является неотъемлемой частью имени файла. Абсолютным (полным) именем файла называется путь от корневой директории, относительным — путь от текущей (рабочей) директории. В одной директории не может быть файлов с одинаковым именем.

Относительное имя файла удобно использовать. Можно поместить нужные какой-то программе или проекту файлы в одну директорию, можно использовать структуру поддиректорий для удобства организации и использования дискового пространства. При переносе всей директории на другой носитель или компьютер, проект останется в рабочем состоянии. Относительные пути, как правило, практически не зависят от операционной системы и конкретного компьютера, если вы работаете внутри какой-то директории. Но надо помнить, что относительное имя файла всегда преобразуется в абсолютное при обращении в нему.

В зависимости от операционной системы и файловой системы именование файла обладает рядом особенностей.
```

2021-05-17 15:51 UTC, igsekor commented on tools/doka/file/practice/igsekor.md
> +### Браузер и имена файлов в Интернете
Вроде добавил.

2021-05-17 15:52 UTC, igsekor commented on tools/doka/file/practice/igsekor.md
> +Расширение имени файла часто используется для идентификации формата файла. Это нужно исключительно для интерфейса пользователя и простой фильтрации, сортировки или группировки имён файлов. В операцио
Хорошо, добавлю

2021-05-17 15:52 UTC, igsekor commented on tools/doka/file/index.md
> +Файл — это абстракция, которая пришла из физического мира. До появления компьютеров файлом называли коробку, папку, шнур, пружину и что-то подобное, с помощью которых можно было собрать, упорядочить
Ок :)

2021-05-17 20:10 UTC, nlopin commented on tools/doka/file/index.md
> +С появлением магнитных лент для хранения данных стали использовать другую модель — последовательность записей переменной длины. Считать с магнитной ленты данные или записать их на неё можно только по
на порядок круче! 👍

2021-05-17 20:11 UTC, nlopin commented on tools/doka/file/index.md
> +Когда появились перфокарты, данные стали разделять на записи постоянной длины, поскольку на одной перфокарте умещалось [определённое количество](https://ru.wikipedia.org/wiki/Перфокарта) машинных сло
```suggestion
Когда появились перфокарты, данные стали разделять на записи постоянной длины, поскольку на одной перфокарте умещалось [определённое количество](https://ru.wikipedia.org/wiki/Перфокарта) машинных слов. _Файлом_ стали называть набор перфокарт с нужными данными. Доступ оставался последовательным, но загрузить можно было произвольный файл, отдав компьютеру нужную стопку перфокарт.
```

2021-05-17 20:12 UTC, nlopin commented on tools/doka/file/index.md
> +Первой моделью организации файлов была одноуровневая(может сказать плоская?) файловая система. Использовать такую файловую систему неудобно, если в операционной системе работает несколько пользовател
```suggestion
Первой моделью организации файлов была одноуровневая (или плоская) файловая система. Использовать такую файловую систему неудобно, если в операционной системе работает несколько пользователей и используется большое количество файлов. Однако одноуровневые файловые системы до сих пор применяются для определённых устройств. Например, в стиральных машинах или в микроволновых печах.
```

2021-05-17 20:36 UTC, igsekor commented on tools/doka/file/index.md
> +С появлением магнитных лент для хранения данных стали использовать другую модель — последовательность записей переменной длины. Считать с магнитной ленты данные или записать их на неё можно только по
@nlopin крутые замечания и предложения!

2021-05-21 08:38 UTC, nlopin approved these changes

2021-05-21 08:39 UTC, merged