Шаблонные строки
Y-Doka/content pull request #512
Opened 2021-05-11 19:48 UTC by Windrushfarer

Closes #372

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +<!-- prettier-ignore -->
А мы же вроде выключили Претиер для всего контента? Или это после переезда в новый репозиторий вернулось?

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Шаблонные строки появились, чтобы помочь решить недостатки обычных строк. Например когда мы используем обычные строки через двойные или одинарные кавычки, то когда в строке необходимо использовать та
```suggestion
Шаблонные строки появились, чтобы помочь решить недостатки обычных строк. Например, когда мы используем обычные строки, то символы кавычек внутри приходится экранировать обратным слэшем `\`.
```

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Можно просто использовать другие кавычки, но наличие обратных слэшов все-равно влияет на читаемость. В шаблонной строке никакое экранирование не нужно (кроме, конечно, самого символа обратной кавычки
```suggestion
Можно просто использовать другие кавычки, но наличие обратных слэшов все равно влияет на читаемость. В шаблонной строке никакое экранирование не нужно (кроме, конечно, самого символа обратной кавычки).
```

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Второй недостаток в обычных строках заключается в отсутствии удобной возможности сделать их многострочными. Чтобы сделать переносы в строку нужно явно добавлять спецсимвол `\n`.
Давай в каждый пункт подзаголовок добавим, чтобы была структура?

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +В обычных строках чтобы подставить значение в строку необходимо использовать конкатенацию через оператор `+`.
Я бы поставил это на первое место. Кажется, что это самое важное, что шаблонные строки дают. (У них даже в названии «шаблон».)

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Шаблонная строка записывается с помощью обратных кавычек. В отличии от обычных строек закрывающей обратной кавычке необязательно быть на той же строчке, что и открывающая, потому что шаблонные строки
```suggestion
Шаблонная строка записывается с помощью обратных кавычек. В отличие от обычных строк закрывающей обратной кавычке необязательно быть на той же строчке, что и открывающая, потому что шаблонные строки могут состоять из нескольких строк.
```

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Шаблонные строки дополнительно открыли функциональность для использования теговых шаблонов. Теговый шаблон – это функция, которая позволяет разбирать шаблонную строку. В такую функцию первым параметр
Сюда бы тоже подзаголовок?.. 🤔

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +  console.log(templString);
Переменная `templString` не объявлена. Тут надо синхронизировать название переменной с аргументом функции.

2021-05-12 07:35 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +Теговому шаблону правда необязательно возвращать именно строку, т.к это обычная функция, то вернуть можно что-угодно, либо вообще ничего.
```suggestion
Теговому шаблону правда необязательно возвращать именно строку, т.к это обычная функция, то вернуть можно что угодно, либо вообще ничего.
```

2021-05-12 14:15 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +В обычных строках чтобы подставить значение в строку необходимо использовать конкатенацию через оператор `+`.
А мне наоборот нравится этот нарратив от малых проблем к главной :)

2021-05-12 14:47 UTC, bespoyasov commented on js/doka/template-strings/index.md
> +В обычных строках чтобы подставить значение в строку необходимо использовать конкатенацию через оператор `+`.
No pressure 😃

2021-05-16 20:55 UTC, nlopin requested changes
Класс 👍

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +name: template-strigns
```suggestion
name: template-strings
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +Шаблонные строки это еще один способ создания строк наравне с одинарными или двойными кавычками и объявляются в обратных кавычках. Но в отличие от других шаблонная строка может быть многострочной, вс
Как тебе такой вариант? Сделал предложения поменьше

```suggestion
Шаблонные строки — это еще один способ создания строк, наравне с одинарными или двойными кавычками. Шаблонные строки объявляются с помощью обратных кавычек. 

Шаблонная строка может быть многострочной, все переносы строк в ней будут сохранены. В шаблонной строке с помощью синтаксиса `${ }` можно использовать любые [выражения](/js/doka/expressions-vs-statements) JavaScript. Любой нестроковый результат (например, объект) будет приведет к строке. 

Шаблонные строки сейчас — основной способ работы со строками, в которые нужно подставлять вычесленные значения.
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +<!-- prettier-ignore -->
такой же вопрос

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +`Hello ${name}!`; // Привет Федя!
классные примеры!

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +Выглядит не очень удобно, даже если записать их на отдельных строках в редакторе. В шаблонных строках можно делать переносы строк как в обычном тексте и все они сохранятся.
```suggestion
Выглядит не очень удобно, даже если записать их на отдельных строках в редакторе. В шаблонных строках можно делать переносы как в обычном тексте, и все они сохранятся.
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +При этом так же будут сохранены все пробелы и табуляции в начале строк. Это особенно может быть удобно для написания html-разметки в строке.
```suggestion
Сохранены будут все пробелы и табуляции в начале строк. Это может быть удобно для написания html-разметки в строке.
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +В обычных строках чтобы подставить значение в строку необходимо использовать конкатенацию через оператор `+`.
Я тоже считаю это главным преимуществом, но если мы явно в тексте скажем, что это самая главная штука, то будет норм

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +В итоге получается нужная нам строка, но для каждого такого динамического значения необходимо явно добавлять оператор плюс и дробить строку на части, если между динамическими частями есть статические
```suggestion
В итоге получается нужная нам строка, но для каждого такого динамического значения необходимо явно добавлять оператор `+` и дробить строку на части, если между динамическими частями есть статические. 

Шаблонные строки предоставляют возможность использовать [строковую интерполяцию](https://en.wikipedia.org/wiki/String_interpolation), проще говоря, подставлять значения прямо в строку. Делается это через с помощью конструкции из знака доллара и фигурных скобок `${ }`
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +Такая составная строка выглядит и читается как одна и добавлять в нее новые динамические значения гораздо проще. Из-за возможности удобного подстановки динамических значений (и следовательно возможно
```suggestion
Такая составная строка выглядит и читается как одна. Добавлять в неё новые динамические значения намного проще. Из-за возможности удобного подстановки динамических значений шаблонные строки получили свое название.
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/index.md
> +Для того, чтобы использовать выражение внутри шаблонной строки необходимо использовать специальную конструкцию: знак доллара вместе с фигурными скобками `${выражение}`. В фигурных скобках должно нахо
```suggestion
Чтобы использовать выражение внутри шаблонной строки, используйте специальную конструкцию: знак доллара вместе с фигурными скобками `${выражение}`. В фигурных скобках должно находится выражение, его результат и будет подставляен в итоговую строку.
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/practice/windrusfarer.md
> +🛠 Несмотря на все плюсы шаблонных строк использовать их везде не имеет смысла. В коде можно отлично смешивать использование тех и других строк: использовать обычные строки для статических значений, а
Давай упрощать:

```suggestion
🛠  В коде можно смешивать использование тех и других строк: использовать обычные строки для статических значений, а для динамических – шаблонные строки. 
```

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/practice/windrusfarer.md
> +🛠 Шаблонные строки могут быть очень полезны если в коде записывается html в строках, либо текст смешивается с html-тегами
я не понял предложения. давай переформулируем

2021-05-16 20:55 UTC, nlopin commented on js/doka/template-strings/practice/windrusfarer.md
> +Будьте осторожны при написании html внутри шаблонных строк, т.к. шаблонные строки, так же как и обычные, не экранируют автоматически спецсимволы. Это значит что использование ненадежного html из шабл
```suggestion
Будьте осторожны при написании html внутри шаблонных строк. Шаблонные строки, так же как и обычные, не экранируют спецсимволы. Это значит что использование ненадежного html из шаблонной строки может привести к различным [атакам](/js/articles/web-security).
```

2021-05-23 14:45 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +<!-- prettier-ignore -->
Ага. Это у меня редактор автоматически все ломал. Убрал

2021-05-23 14:50 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +В обычных строках чтобы подставить значение в строку необходимо использовать конкатенацию через оператор `+`.
Мне честно говоря не кажется, что это прям надо супер-супер выделять. Я добавил предложение, но там и ранее было, что за эту фичу шаблонные строки получили свое название ¯\_(ツ)_/¯

2021-05-23 14:53 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +Шаблонные строки это еще один способ создания строк наравне с одинарными или двойными кавычками и объявляются в обратных кавычках. Но в отличие от других шаблонная строка может быть многострочной, вс
Звучит хорошо, взял его

2021-05-23 14:55 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +При этом так же будут сохранены все пробелы и табуляции в начале строк. Это особенно может быть удобно для написания html-разметки в строке.
Насчет второго предложения согласен, слишком много выделения. Но в первом я намеренно использовал оборот "при этом", чтобы выделить эту особенность. Думаешь не стоит?

2021-05-23 15:01 UTC, Windrushfarer commented on js/doka/template-strings/index.md
> +При этом так же будут сохранены все пробелы и табуляции в начале строк. Это особенно может быть удобно для написания html-разметки в строке.
Переформулировал, должно стать лучше

2021-05-24 13:32 UTC, bespoyasov reviewed
Как по мне всё отлично 🙂 
@nlopin?

2021-05-26 10:43 UTC, nlopin approved these changes
LGTM

2021-05-26 10:48 UTC, merged