Добавляет статью про <embed>
Y-Doka/content pull request #518
Opened 2021-05-13 11:57 UTC by solarrust

Close #388

2021-05-13 17:24 UTC, pepelsbey requested changes

2021-05-13 17:24 UTC, pepelsbey commented on html/doka/embed/index.md
> +- `height` — высота окна в пикселях, проценты не допустимы. Указывается только число, без единиц измерения.
```suggestion
- `width` — ширина в пикселях, проценты не допустимы. Указывается только число, без единиц измерения.
- `height` — высота в пикселях, проценты не допустимы. Указывается только число, без единиц измерения.
```

Тут «окно» неоднозначно звучит, как будто сюда нужно вставить ширину окна браузера.

2021-05-13 17:24 UTC, pepelsbey commented on html/doka/embed/index.md
> +- `height` — высота окна в пикселях, проценты не допустимы. Указывается только число, без единиц измерения.
```suggestion
- `width` и `height` — ширина и высота в пикселях, проценты не допустимы. Указывается только число, без единиц измерения.
```

Может даже сократить? Одинаковые описания тратят время читателя )

2021-05-13 17:24 UTC, pepelsbey commented on html/doka/embed/index.md
> +![Сообщение в браузере «Плагин не поддерживается»](images/no-plugin.jpg)
````suggestion

```html
<embed src="player.swf" type="application/x-shockwave-flash">
```

![Сообщение в браузере «Плагин не поддерживается»](images/no-plugin.jpg)
````

Предлагаю показать пример того самого плагина, который не поддерживается и реальную более качественную картинку в PNG:

![image](https://user-images.githubusercontent.com/105274/118162203-26a5f000-b429-11eb-99b6-ebf7da242b9d.png)

Если нравится, закоммичу её с правкой пути.

2021-05-14 13:25 UTC, solarrust commented on html/doka/embed/index.md
> +![Сообщение в браузере «Плагин не поддерживается»](images/no-plugin.jpg)
У меня просто без имени плагина показывается уведомление. Твоя картинка ок, информативнее =)

2021-05-14 13:31 UTC, solarrust commented
@pepelsbey забрала твою картиночку, вынесла повторяющееся описание. Можно проверить ещё раз.

2021-05-15 06:35 UTC, tachisis reviewed
Чуточка правочек

2021-05-15 06:35 UTC, tachisis commented on html/doka/embed/index.md
> +Магический блок для вставки на страницу контента в непонятных браузеру форматах. Чаще всего используется для видео- и аудиоконтента.
```suggestion
Магический блок для вставки на страницу контента в сторонних форматах, которые браузер отображает с помощью плагинов. Чаще всего используется для видео- и аудиоконтента.
```

2021-05-15 06:35 UTC, tachisis commented on html/doka/embed/index.md
> +Магический блок для вставки на страницу контента в непонятных браузеру форматах. Чаще всего используется для видео- и аудиоконтента.
Хотелось сформулировать почетче, что значит «непонятных», а то сликшом много мистики в одном абзаце. Не знаю, угадала ли с другой формулировкой, можно переделать.

2021-05-15 06:35 UTC, tachisis commented on html/doka/embed/index.md
> +- `type` — тип загружаемого контента в формате [MIME](https://ru.wikipedia.org/wiki/Список_MIME-типов). Тип указывать не обязательно, но желательно. Так браузер точно будет знать, какой плагин исполь
```suggestion
- `type` — тип загружаемого контента в формате [MIME](https://ru.wikipedia.org/wiki/Список_MIME-типов). Тип указывать не обязательно, но желательно. Так браузер будет точно знать, какой плагин использовать для отображения контента.
```

2021-05-15 06:35 UTC, tachisis commented on html/doka/embed/index.md
> +При указании ширины и высоты проценты не допустимы. Указывается только число, без единиц измерения.
```suggestion
При указании ширины и высоты проценты недопустимы. Указывается только число, без единиц измерения.
```

2021-05-15 06:35 UTC, tachisis commented on html/doka/embed/index.md
> +💡 Если на пользователе компьютера не установлен нужный для отображения контента плагин, то он увидит в окне предупреждение:
```suggestion
💡 Если на компьютере пользователя не установлен нужный для отображения контента плагин, то он увидит в окне предупреждение:
```

2021-05-15 07:00 UTC, tachisis commented on html/doka/embed/index.md
> +  - solarrust
```suggestion
  - solarrust
editor: tachisis
```

2021-05-17 12:04 UTC, pepelsbey commented
@solarrust я немного обновил демку, чтобы она интереснее выглядела, что скажешь?

<img width="720" alt="image" src="https://user-images.githubusercontent.com/105274/118485402-12ac0800-b721-11eb-800d-0d24cc5cb997.png">

Там видно страницу, на которую встроено окно в PDF. Я бы сам PDF-файл сделал повеселее и на русском. Запросишь у Вали?

2021-05-17 12:07 UTC, solarrust commented
> @solarrust я немного [обновил демку](https://github.com/Y-Doka/content/pull/518/commits/f5e19a46fce9b6f7cf74a0b624769f693fc62d73), чтобы она интереснее выглядела, что скажешь?
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/105274/118485402-12ac0800-b721-11eb-800d-0d24cc5cb997.png">
> 
> Там видно страницу, на которую встроено окно в PDF. Я бы сам PDF-файл сделал повеселее и на русском. Запросишь у Вали?

Выглядит отлично =) Я делала демку с расчётом, что потом заглянет Света и сделает всё красиво. Но я не против твоего варианта. Давай PDF оставим на попозже, кажется, сейчас и с шаблоном ок.

2021-05-17 12:14 UTC, pepelsbey commented
> Я делала демку с расчётом, что потом заглянет Света и сделает всё красиво

Я решил очень просто сделать чуть лучше :)

2021-05-17 12:14 UTC, pepelsbey approved these changes

2021-05-17 14:06 UTC, tachisis approved these changes

2021-05-17 14:06 UTC, merged