Редактирует статью про ol
Y-Doka/content pull request #520
Opened 2021-05-15 07:45 UTC by tachisis

2021-05-15 07:46 UTC, tachisis commented on html/doka/ol/practice/ezhkov.md
> +🛠 Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны пле
> Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация

Это на самом деле очень загадочное предложение (и было, и осталось), потому что я не понимаю, что хотел сказать автор. Может быть, нужен какой-то более явный пример.

2021-05-17 10:16 UTC, solarrust commented on html/doka/ol/practice/ezhkov.md
> +🛠 Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны пле
@ezhkov загляни сюда, может быть сможешь пояснить смысл =)

2021-05-18 10:15 UTC, tachisis commented on html/doka/ol/index.md
> +editor:
```suggestion
editors:
```

2021-05-19 11:06 UTC, ezhkov requested changes

2021-05-19 11:06 UTC, ezhkov commented on html/doka/ol/practice/ezhkov.md
> +🛠 Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны пле
Можно заменить на "Тег `<ol>` чаще всего используется для разметки нумерованных списков в тексте. Другой вариант... "

2021-05-20 17:25 UTC, tachisis commented on html/doka/ol/practice/ezhkov.md
> +🛠 Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны пле
```suggestion
🛠 Тег <ol> чаще всего используется для разметки нумерованных списков в тексте. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны плейлисты в музыкальной библиотеке.
```

2021-05-20 17:25 UTC, tachisis commented on html/doka/ol/practice/ezhkov.md
> +🛠 Упорядоченные списки на сайтах могут использоваться в текстах, где явно требуется нумерация. Другой вариант использования часто можно увидеть на медиасервисах: упорядоченными списками свёрстаны пле
Отличный вариант, спасибо, заменила!

2021-05-21 08:45 UTC, solarrust approved these changes

2021-05-21 08:45 UTC, merged