Обновляет инструкцию
Y-Doka/content pull request #699
Opened 2021-05-20 10:57 UTC by furtivite

Старая инструкция устарела. Обновил техническую часть.

2021-05-20 11:01 UTC, furtivite commented
@tachisis видел, что спеллер упал, решение по встраиванию новых слов в словарь, не за мной)

2021-05-20 13:20 UTC, pepelsbey reviewed
Предлагаю переформулировать

2021-05-20 13:20 UTC, pepelsbey commented on docs/contributing.md
> +Дока состоит из двух репозиториев. Контентного, в котором вы находитесь сейчас, и [платформенного](https://github.com/Y-Doka/platform), который собирает сайт на базе [Eleventy — генератора статически
```suggestion
Дока состоит из двух репозиториев:

 1. Контент, в котором вы находитесь сейчас;
 2. [Платформа](https://github.com/Y-Doka/platform), который собирает сайт на базе [Eleventy](https://www.11ty.dev/).
 
Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на Гитхабе — он поможет вам предложить их в пулреквесте. Если вы пишете новую статью или делаете обширные правки, то лучше форкните репозиторий, склонируйте его себе локально и откройте в любимом редакторе кода.
```

2021-05-20 13:20 UTC, pepelsbey commented on docs/contributing.md
> +Если вам нужен предпросмотр, [прочите интрукцию](https://github.com/Y-Doka/content/blob/main/docs/preview.md). Спойлер: вам потребуется Docker.
```suggestion
Если вы хотите посмотреть, как ваша статья или правки выглядят и собираются в полноценный сайт, то вам [поможет интрукция](https://github.com/Y-Doka/content/blob/main/docs/preview.md). Спойлер: вам потребуется Docker.
```

2021-05-20 13:23 UTC, pepelsbey requested changes
Ещё правки по демкам

2021-05-20 13:23 UTC, pepelsbey commented on docs/contributing.md
> +Встроенные в страницу «демки» позволяют плавнее строить повествование и демонстрацию концепций.
```suggestion
Встроенные в страницу демки позволяют плавнее строить повествование и демонстрацию концепций.
```

2021-05-20 13:23 UTC, pepelsbey commented on docs/contributing.md
> +Технически демка может состоять из любого набора файлов в папке `/includes/demos`, но чаще всего это обычный html-файл со стилями в `<head></head>` и скриптами в `<body></body>`. Посмотрите [пример д
```suggestion
Подробнее про демки читайте [в отдельном документе](demos.md).
```

2021-05-20 13:41 UTC, pepelsbey commented on docs/contributing.md
> +Дока состоит из двух репозиториев. Контентного, в котором вы находитесь сейчас, и [платформенного](https://github.com/Y-Doka/platform), который собирает сайт на базе [Eleventy — генератора статически
Дока состоит из двух репозиториев:

 1. Контент, в котором вы находитесь сейчас;
 2. [Платформа](https://github.com/Y-Doka/platform), который собирает сайт на базе [Eleventy](https://www.11ty.dev/).
 
Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на Гитхабе — он поможет вам предложить их в пулреквесте. Если вы пишете новую статью или делаете обширные правки, то лучше форкните репозиторий, склонируйте его себе локально и откройте в любимом редакторе кода.

2021-05-20 13:42 UTC, pepelsbey commented
> @tachisis видел, что спеллер упал, решение по встраиванию новых слов в словарь, не за мной)

Там не только новые слова, там ещё просто опечатки.

2021-05-20 14:01 UTC, furtivite commented on docs/contributing.md
> +Если вы хотите посмотреть всю Доку локально без Docker, [в инструкции](https://github.com/Y-Doka/platform/blob/main/docs/how-to-run.md) расказано, как запустить платформу с симлинками.
```suggestion
Если вы хотите посмотреть всю Доку локально без Docker, [в инструкции](https://github.com/Y-Doka/platform/blob/main/docs/how-to-run.md) расказано, как запустить платформу с симлинками.
```

Если вы хотите посмотреть всю Доку локально без Docker, [в инструкции](https://github.com/Y-Doka/platform/blob/main/docs/how-to-run.md) рассказано, как запустить платформу с симлинками.

2021-05-20 17:17 UTC, tachisis reviewed
Немного правочек, и одобряю все от Вадима

2021-05-20 17:17 UTC, tachisis commented on docs/contributing.md
> +Если вам нужен предпросмотр, [прочите интрукцию](https://github.com/Y-Doka/content/blob/main/docs/preview.md). Спойлер: вам потребуется Docker.
```suggestion
Если вам нужен предпросмотр, [прочите инструкцию](https://github.com/Y-Doka/content/blob/main/docs/preview.md). Спойлер: вам потребуется Docker.
```

2021-05-20 17:17 UTC, tachisis commented on docs/contributing.md
> +У каждой статьи есть своя папка со своей папкой картинок, демок, видео, аудио и практик (блок «В работе»).
```suggestion
У каждой статьи есть своя папка с подпапками для картинок, демок, видео, аудио и практик (блок «В работе»).
```

2021-05-20 17:17 UTC, tachisis commented on docs/contributing.md
> +В контентном репозитории мы пишем относительные пути. Например так выглядит ссылка на демку из блока «В работе», которые лежат на уровень выше:
```suggestion
В контентном репозитории мы пишем относительные пути. Например, так выглядит ссылка на демку из блока «В работе», которая лежит на уровень выше:
```

2021-05-20 17:17 UTC, tachisis commented on docs/contributing.md
> +Какого-то из полей в шапке может не хватать, потому что он пока не используется. Если поле пустое: мы его не пишем, если нужно добавить новое, добавляем.
```suggestion
Какого-то из полей в шапке может не хватать, потому что оно пока не используется. Если поле пустое: мы его не пишем, если нужно добавить новое, добавляем.
```

2021-05-21 08:52 UTC, pepelsbey approved these changes

2021-05-21 14:49 UTC, tachisis approved these changes

2021-05-24 09:31 UTC, merged