Добавляет лицензии
Y-Doka/content pull request #703
Opened 2021-05-21 08:52 UTC by furtivite

- Добавляет лицензию на весь контент, кроме графического

2021-05-21 13:30 UTC, pepelsbey reviewed
Я подредактировал имена файлов, но у меня остался вопрос: а нам нужен такой суровый документ? Мне кажется, что двух убористых лицензий более чем достаточно. А в документации нужно очень просто сказать: с текстом делайте что хотите, картинки не надо править. И не забывайте про нас упоминать, когда цитируете.

2021-05-21 13:33 UTC, furtivite commented
@pepelsbey кажется, переусложнил.

2021-05-21 14:48 UTC, tachisis reviewed
Поредактировала как есть, на случай, если не будет сокращений

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +**Обратите внимание: здесь вы прочитаете упрощённую русскоязычную версию лицензии. Все юридически-значимые документы лежат в своих репозиториях и доступны на английском языке.**
```suggestion
**Обратите внимание: здесь вы прочитаете упрощённую русскоязычную версию лицензии. Все юридически значимые документы лежат в своих репозиториях и доступны на английском языке.**
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Вы должны обеспечить соответствующее указание авторства, предоставить ссылку на лицензию, и обозначить изменения, если таковые были сделаны.](images/license/by.png)
```suggestion
![Вы должны обеспечить соответствующее указание авторства, предоставить ссылку на лицензию, и обозначить изменения, если таковые были сделаны](images/license/by.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Если вы перерабатываете, преобразовываете материал или берёте его за основу для производного произведения, вы должны распространять переделанные вами части материала на условиях той же лицензии, в
```suggestion
![Если вы перерабатываете, преобразовываете материал или берёте его за основу для производного произведения, вы должны распространять переделанные вами части материала на условиях той же лицензии, в соответствии с которой распространяется оригинал](images/license/sa.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Вы не вправе использовать этот материал в коммерческих целях.](images/license/nc.png)
```suggestion
![Вы не вправе использовать этот материал в коммерческих целях](images/license/nc.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +Все тексты, представленные на нашем сайте и в этом репозитории распространяются по лицензии [Creative Commons «Attribution-NonCommercial-ShareAlike» (CC BY-NC-SA 4.0)](../LICENSE-SA.md).
```suggestion
Все тексты, представленные на нашем сайте и в этом репозитории, распространяются по лицензии [Creative Commons «Attribution-NonCommercial-ShareAlike» (CC BY-NC-SA 4.0)](../LICENSE-SA.md).
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +1. Адаптировать (создавать производные материалы) — делать ремиксы, видоизменять, и создавать новое, опираясь на этот материал.
```suggestion
1. Адаптировать (создавать производные материалы) — делать ремиксы, видоизменять и создавать новое, опираясь на этот материал.
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +1. Всегда указывать автора и давать ссылку на на лицензию. Если вы сделали изменения, об этом надо сообщить, но не в стиле, что автор оригинала эти изменения одобрил.
```suggestion
1. Всегда указывать автора и давать ссылку на лицензию. Если вы сделали изменения, об этом надо сообщить, но не в стиле, что автор оригинала эти изменения одобрил.
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +1. Всегда указывать автора и давать ссылку на на лицензию. Если вы сделали изменения, об этом надо сообщить, но не в стиле, что автор оригинала эти изменения одобрил.
Не понимаю, что значит «не в стиле»

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Вы должны обеспечить соответствующее указание авторства, предоставить ссылку на лицензию, и обозначить изменения, если таковые были сделаны.](images/license/by.png)
```suggestion
![Вы должны обеспечить соответствующее указание авторства, предоставить ссылку на лицензию, и обозначить изменения, если таковые были сделаны](images/license/by.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Если вы перерабатываете, преобразовываете материал или берёте его за основу для производного произведения, вы не можете распространять измененный материал.](images/license/nd.png)
```suggestion
![Если вы перерабатываете, преобразовываете материал или берёте его за основу для производного произведения, вы не можете распространять измененный материал](images/license/nd.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +![Вы не вправе использовать этот материал в коммерческих целях.](images/license/nc.png)
```suggestion
![Вы не вправе использовать этот материал в коммерческих целях](images/license/nc.png)
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +Все «не тексты», представленные на нашем сайте и в этом репозитории распространяются по лицензии [Creative Commons  «Attribution-NonCommercial-NoDerivatives» (CC BY-NC-ND 4.0)](../LICENCE-ND.md).
```suggestion
Все «не тексты», представленные на нашем сайте и в этом репозитории, распространяются по лицензии [Creative Commons  «Attribution-NonCommercial-NoDerivatives» (CC BY-NC-ND 4.0)](../LICENCE-ND.md).
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +1. Делиться (обмениваться) — копировать и распространять материал на любом носителе и в любом формате
```suggestion
1. Делиться (обмениваться) — копировать и распространять материал на любом носителе и в любом формате.
```

2021-05-21 14:48 UTC, tachisis commented on docs/license.md
> +Когда вы делаете свой вклад вы передаёте право [команде Доки](https://github.com/orgs/Y-Doka/people) использовать ваш труд для Доки в любой форме, определённой лицензиями, которые мы описали.
```suggestion
Когда вы делаете свой вклад, вы передаёте право [команде Доки](https://github.com/orgs/Y-Doka/people) использовать ваш труд для Доки в любой форме, определённой лицензиями, которые мы описали.
```

2021-05-24 09:38 UTC, furtivite commented
Сильно сократил и упростил текст. Кажется, можно проверить.

2021-05-24 10:24 UTC, pepelsbey requested changes

2021-05-24 10:24 UTC, pepelsbey commented on docs/license.md
> +Наши тексты распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License](../content/LICENSE-SA.md).
```suggestion
Наши тексты распространяются по лицензии [CC BY-NC-SA 4.0](../content/LICENSE-SA.md).
```

2021-05-24 10:24 UTC, pepelsbey commented on docs/license.md
> +![Сохраняй лицензию](./images/license/sa.png)
```suggestion
<img src="images/license/cc.png" width="35" height="35" alt="Creative Commons">
<img src="images/license/by.png" width="35" height="35" alt="Сохранение ссылок и авторства">
<img src="images/license/nc.png" width="35" height="35" alt="Некоммерческое использование">
<img src="images/license/sa.png" width="35" height="35" alt="Сохранение лицензии">
```

Так картинки выглядят лучше на ретине (и лучше грузятся)

2021-05-24 10:24 UTC, pepelsbey commented on docs/license.md
> +![Не изменяй](./images/license/nd.png)
```suggestion
<img src="images/license/cc.png" width="35" height="35" alt="Creative Commons">
<img src="images/license/by.png" width="35" height="35" alt="Сохранение ссылок и авторства">
<img src="images/license/nc.png" width="35" height="35" alt="Некоммерческое использование">
<img src="images/license/nd.png" width="35" height="35" alt="Неизменность">
```

2021-05-24 10:24 UTC, pepelsbey commented on docs/license.md
> +Всё, что находится в Доке, кроме текста и не распространяется по другим правилам, защищается [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License](../content/LIC
```suggestion
Всё остальное в Доке, кроме текста, распространяется по лицензии [CC BY-NC-ND 4.0](../content/LICENCE-ND.md).
```

2021-05-24 10:54 UTC, pepelsbey commented
[Заменил картинки на векторные](https://github.com/Y-Doka/content/pull/703/commits/def5d6044258dbe71b4ba725027eaa1fc19f4b7b): это позволяет их проще вставлять и они круче выглядят.

2021-05-24 10:54 UTC, pepelsbey approved these changes
Получилось очень круто!

2021-05-24 12:55 UTC, tachisis approved these changes

2021-05-24 13:06 UTC, merged