Добавляет три связанных статьи
Y-Doka/content pull request #720
Opened 2021-05-26 13:46 UTC by igsekor

Список статей:

1. Работа с сетью;
2. Многозадачность и управление процессами;
3. Веб-сервер.

2021-05-26 18:37 UTC, pepelsbey requested changes

2021-05-26 18:37 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +    listen 8080;
А можно писать конфиги с отступом 2 пробела, nginx это поймёт?

2021-05-26 18:37 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +С помощью директив к nginx подключаются модули, которые и обеспечивают основной функционал. Директивы делятся на простые. состоящие из строки имён, разделённых пробелами, с `;` в конце, и блочные, за
Очень сложная формулировка о типах директив. Их бы выделить в список и показать пример (как ниже), а не рассказать словами (разделённая пробелами с `;` в конце).

2021-05-26 18:37 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +Если конфигурационный файл написан правильно, то nginx об это сообщит в Терминале, равно как и укажет на ошибки при их наличии.
```suggestion
Если конфигурационный файл написан правильно, то nginx об это сообщит в консоли, равно как и укажет на ошибки при их наличии.
```

Чтобы не звучало как название моего любимого бара )

2021-05-26 18:37 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +При этом веб-сервер ожидает, что соответствующий модуль прослушивает порт 9000 на этом же компьютере. Настройку для пакетов на компьютере можно сделать, как этом описано [здесь](/tools/articles/netwo
```suggestion
При этом веб-сервер ожидает, что соответствующий модуль прослушивает порт 9000 на этом же компьютере. Читайте подробнее, [как сделать настройку для пакетов на компьютере](/tools/articles/network).
```

Для ссылок лучше избегать слов «тут», «здесь», «сюда» и вешать её на значимые слова. Это и доступнее, и сеошникам нравится больше.

2021-05-27 12:38 UTC, pepelsbey requested changes

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/network/practice/igsekor.md
> +Использование команды `man` подробно описано [здесь](/tools/articles/cli).
```suggestion
Использование команды `man` подробно описано в статье «[Интерфейс командной строки](/tools/articles/cli)».
```

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/network/practice/igsekor.md
> +- пакет, представленный в бинарном виде.
Лучше одну картинку, чем пару сотню слов :)

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/network/practice/igsekor.md
> +Вы можете получить подробную информацию о каждом пакете, нужно лишь выбрать его из списка. Пакеты можно фильтровать по различным признакам. Существуют фильтры захвата и показа. Первый тип фильтров ис
Если интерфейс не локализован, то лучше оригинальные названия давать сначала, а потом переводить в скобках.

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/network/practice/igsekor.md
> +Пока вы не прервете работу утилиты сигналом `SIGINT` (подробнее [здесь](/tools/articles/process-management)), нажав сочетание клавиш <kbd>Ctrl C</kbd>, в терминал будет выводиться информация о пакета
Добавить бы названия статей вместо «здесей» :)

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/process-management/practice/igsekor.md
> +Иногда удобнее использовать фоновые процесс. Например, если мы хотим все время посылать запросы сетевому устройству с помощью команды `ping`, как это было описано [здесь](/tools/articles/network):
Здесь — в статье «…»

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +Чтобы перенаправить часть запросов по URI `/` (подробнее об это [здесь](/tools/articles/network) ) приложению или службе, запущенной на компьютере и прослушивающей порт 8080, а часть запросов по пути
Здесь — в статье «…»

2021-05-27 12:38 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +Можно получить конфигурационный файл с помощью специального [сервиса](https://ssl-config.mozilla.org). Попробовать сгенерировать разные конфигурации позволит разобраться с конкретными настройками дет
```suggestion
Можно получить конфигурационный файл с помощью сервиса [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org). Попробовать сгенерировать разные конфигурации позволит разобраться с конкретными настройками детальнее.
```

2021-05-27 19:04 UTC, nlopin requested changes

2021-05-27 19:04 UTC, nlopin commented on tools/articles/network/index.md
> +Сетевая служба — это способ организации передачи данных на уровне операционной системы. Сетевые сервисы — это конкретные приложения / службы / демоны, которые работают в качестве поставщика данных: в
Давай здесь попробуем убрать определения и построить повестование? Если не будет получаться, то тоже ок

2021-05-27 19:04 UTC, nlopin commented on tools/articles/network/practice/igsekor.md
> +Пока вы не прервете работу утилиты сигналом `SIGINT` (подробнее [здесь](/tools/articles/process-management)), нажав сочетание клавиш <kbd>Ctrl C</kbd>, в терминал будет выводиться информация о пакета
```suggestion
Пока вы не прервете работу утилиты сигналом `SIGINT`, нажав сочетание клавиш <kbd>Ctrl C</kbd>, в терминал будет выводиться информация о пакетах. Прочитайте статью [«Управление процессами»](/tools/articles/process-management), чтобы узнать больше о сигналах.
```

2021-05-28 06:33 UTC, igsekor commented on tools/articles/network/index.md
> +Передача данных в компьютерных сетях возможна благодаря протоколам. Протокол — это набор правил, по которым работают все сетевые устройства. Данные от одного сетевого устройства к другому передаются
Так лучше!

2021-05-28 06:35 UTC, igsekor commented on tools/articles/network/index.md
> +![Передача файла по сети в виде пакетов](images/1.png)
Было бы здорово! Могу помочь?

2021-05-28 06:39 UTC, igsekor commented on tools/articles/network/index.md
> +1. Запрос разбивается на пакеты и отправляется путешествовать по сети Интернет. Адресом целевого сетевого устройства будет ближайший DNS-сервер (DNS — Domain Name System). DNS-сервер — это специальны
Немного перефразировал только.

2021-05-28 06:41 UTC, igsekor commented on tools/articles/network/index.md
> +Сетевая служба — это способ организации передачи данных на уровне операционной системы. Сетевые сервисы — это конкретные приложения / службы / демоны, которые работают в качестве поставщика данных: в
Кажется стало лучше

2021-05-28 06:44 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +- пакет, представленный в бинарном виде.
Добавлю обязательно! :)

2021-05-28 06:44 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +Вы можете получить подробную информацию о каждом пакете, нужно лишь выбрать его из списка. Пакеты можно фильтровать по различным признакам. Существуют фильтры захвата и показа. Первый тип фильтров ис
Интерфейс локализован, я указал правильное название в русифицированной версии.

2021-05-28 06:58 UTC, igsekor commented on tools/articles/webserver/practice/igsekor.md
> +    listen 8080;
Можно, но принято 4.

2021-05-28 07:16 UTC, pepelsbey commented on tools/articles/webserver/practice/igsekor.md
> +    listen 8080;
Я просто думаю, стоит ли нам форсить здесь свой стиль кода или нет. Есть, скажем «принято» как в Python, а есть «принято» как в JS, где, в общем, всё равно. И если всё равно, то кажется, что лучше зафорсить стиль. Но я не уверен :)

2021-05-29 09:29 UTC, igsekor commented on tools/articles/webserver/practice/igsekor.md
> +    listen 8080;
Скорее всего, можно форсить свой стиль :) Видел конфиги, в которых всё сделано табами :)

2021-05-29 09:34 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +Пока вы не прервете работу утилиты сигналом `SIGINT` (подробнее [здесь](/tools/articles/process-management)), нажав сочетание клавиш <kbd>Ctrl C</kbd>, в терминал будет выводиться информация о пакета
Да это правда

2021-05-29 09:36 UTC, igsekor commented on tools/articles/process-management/practice/igsekor.md
> +Иногда удобнее использовать фоновые процесс. Например, если мы хотим все время посылать запросы сетевому устройству с помощью команды `ping`, как это было описано [здесь](/tools/articles/network):
Точно!

2021-05-29 09:37 UTC, igsekor commented on tools/articles/webserver/practice/igsekor.md
> +Чтобы перенаправить часть запросов по URI `/` (подробнее об это [здесь](/tools/articles/network) ) приложению или службе, запущенной на компьютере и прослушивающей порт 8080, а часть запросов по пути
Исправил :)

2021-05-29 09:51 UTC, igsekor commented on tools/articles/process-management/index.md
> +![Очередь готовых к запуску процессов в многопоточных операционных системах](images/2.png)
Надо перерисовать, думаю первый рисунок, чтобы разница была отчётливо. Сделаю.

2021-05-29 09:52 UTC, igsekor commented on tools/articles/process-management/practice/igsekor.md
> +Символ `&` в конце строки команды и означает запуск процесса в фоновом режиме. `<PID>` (от Process Identifier) — идентификационный номер процесса. Зная его, можно отслеживать состояние процесса, пода
Готово

2021-05-29 09:54 UTC, igsekor commented on tools/articles/process-management/practice/igsekor.md
> +Если запустить другой процесс, например, разархивировать другой архив, то вы увидите, что номер сменился:
Точно. Забыл поменять первый вариант примера

2021-05-29 09:54 UTC, igsekor commented on tools/articles/process-management/practice/igsekor.md
> +kill -s SIGHUP <PROCESS_ID>
Да да. Исправил.

2021-05-29 10:11 UTC, igsekor commented on tools/articles/process-management/index.md
> +Процессы разбиваются на операции. Диспетчер распределяет операции процессов в очереди в порядке приоритетов. Такая очередь называется _очередью готовых к запуску_. Приоритет служит основанием для пос
Переписал

2021-05-29 10:31 UTC, igsekor commented on tools/articles/process-management/index.md
> +Существуют ещё и программные прерывания, которые инициируются специальной инструкцией в коде программы. Программные прерывания используются для работы с внешними устройствами (например, в драйверах д
Переписал

2021-05-29 10:43 UTC, igsekor commented on tools/articles/process-management/index.md
> +— <kbd>Ctrl C</kbd> генерирует сигнал `SIGINT`;
Кажется исправил

2021-05-29 10:52 UTC, igsekor commented on tools/articles/process-management/index.md
> +Вскоре выяснилось, что такой механизм не очень работает, поскольку есть множество медленных операций по сравнению со скоростью процессора. Например, это могли быть вывод данных на печать или запрос д
Переписал

2021-05-29 11:02 UTC, igsekor commented on tools/articles/process-management/index.md
> +### Процессы и ресурсы
Переделал

2021-05-29 11:27 UTC, igsekor commented on tools/articles/process-management/index.md
> +Программа — это совокупность операций над данными, которые осуществляет процесс. В рамках процесса нужно рассматривать программу как последовательность инструкций для процессора, которые загружены в
Переписал

2021-05-29 11:28 UTC, igsekor commented on tools/articles/process-management/index.md
> +---
Написал по-другому. Как тебе такой вариант?

2021-05-29 11:32 UTC, igsekor commented on tools/articles/webserver/practice/igsekor.md
> +С помощью директив к nginx подключаются модули, которые и обеспечивают основной функционал. Директивы делятся на простые. состоящие из строки имён, разделённых пробелами, с `;` в конце, и блочные, за
Переделал

2021-05-30 09:03 UTC, igsekor commented on tools/articles/process-management/index.md
> +![Очередь готовых к запуску процессов в многопоточных операционных системах](images/2.png)
Перерисовал

2021-05-31 06:58 UTC, ValyaBro commented on tools/articles/network/index.md
> +![Передача файла по сети в виде пакетов](images/1.png)
да можем анимашку! Это будет mp4. Да, если получится сделать раскадровку будет супер )

2021-05-31 09:35 UTC, ValyaBro requested changes
tools/articles/network/images/1.png -> сейчас связи получились довольно хаотичными и трудно воспринимаемыми. Давай попробуем добавить больше привязки к сетке и сделать все стрелки или прямыми, или под углом 45 без изломов, или с изломом под 90 градусов? по моим ощущениям должна сработать компоновка всех сетевых устройств в одну вертикаль. + давай сделаем заголовок к схеме заголовком (Roboto Bold 64, в верхней части изображения, по центру)
![2021-05-31 12 34 11](https://user-images.githubusercontent.com/42911440/120173279-8ca5bc00-c20c-11eb-877c-85d49dd5d31f.jpg)

2021-05-31 09:40 UTC, ValyaBro requested changes
tools/articles/network/images/2.png -> давай пока попробуем не уходить в квадрат и останемся в имеющихся компонентах? Кажется можно использовать круглые сущности первого уровня и прямоугольники белого и зеленого цветов с крупным текстом на стрелках + положила в фигму компонент "многоточие"

2021-05-31 09:43 UTC, ValyaBro requested changes
tools/articles/network/images/3.png -> хочетс сделать скриншот более ценным и лучше читаемым для пользователя. Давай уменьшим чёрные поля и сделаем значимое изображение крупнее?

2021-05-31 09:53 UTC, ValyaBro requested changes
tools/articles/process-management/images/1.png  +2.png + 3.png -> 

- хочется сделать все схемы крупнее, сейчас остаётся много негативного пространства
- при использовании выбранных сущностей первого уровня получается разных вес шрифтов (подписей блоков), это выглядит немного хаотично и рассеивает внимание. Давай попробуем выровнять кегель шрифта в блоках?
- на стрелках кажется целесообразным использовать сущности второго уровня, а не третьего
- хочется выровнять блоки с описанием процессов по центру
- в третьей схеме хочется сделать компоновку в две колонки, сейчас она выглядит немного хаотично

2021-05-31 09:56 UTC, ValyaBro commented
+ к предыдуще му комменту tools/articles/process-management/images/1.png +2.png + 3.png ->

- сноску лучше прилинковать к правому краю схемы
- хочется сделать используемые цвета более контрастными между собой, сейчас они одной светлоты, будет лучше , если будут разной. Можно посмотреть в ч/б режиме просмотра

2021-05-31 10:07 UTC, ValyaBro requested changes
tools/articles/process-management/images/4.png 

- сейчас в схеме много разных стилистических решений, давай немного их ограничим. Так схема будет выглядеть спокойнее и целостнее:
1. хочется сократить количество цветов до трех включая белый
2. давай не будем уводить выделение группы в край формата
3. хочется сделать выделение групп в одном стиле (обводка 4px, можно менять цвет)
4.есть ли какая-то смысловая связь между сущностями розового цвета? Если есть, то супер! Если нет, то давай подумаем, как избавится от визуальной связи. 
5. подписи "сущность" и "оперативная память" давай сделаем подписями второго уровня (Roboto Bold 40) плюс будет классно расположить их ближе к границе выделяемой области. Сейчас они немного отлетели и не сразу понятно к чему они относятся. Плюс их можно сделать цвета обводки, это добавит визуальной привязки. 
6. Можем попробовать сделать схему работающей и на декстопе, и на мобилке, это реализуется, если скомпоновать все сущности в квадрат.

2021-05-31 10:17 UTC, ValyaBro reviewed
tools/articles/process-management/images/5.png + 6.png
сейчас обе схемы получились довольно детальными и монотонными. Хочется увеличить общий размер, сделать шрифты крупнее и добавить контрастов.

- давай попробуем уменьшить количество округлых форм. 
- зеленый и розовый цвета имеют почти одинаковую светлоту, давай выберем более разнообразные цвета 
- стрелки могут располагаться или под углом 45 градусов (без сгиба), или сгибаться под углом 90 градусов

2021-05-31 10:18 UTC, ValyaBro requested changes
tools/articles/webserver/images/1.png  
хочется уменьшить высоту изображения, сейчас большие чёрные поля сверху и снизу

2021-05-31 10:49 UTC, pepelsbey approved these changes

2021-05-31 10:52 UTC, pepelsbey commented
@ValyaBro нам точно нужны такие большие поля по краям? По сути, это отдаляет картинку от читателя без особых причин.

![image](https://user-images.githubusercontent.com/105274/120182595-443fcb80-c217-11eb-935b-4cfc2257eca7.png)

Мне, как читателю, было бы удобнее смотреть на такую картинку:

![image](https://user-images.githubusercontent.com/105274/120182703-676a7b00-c217-11eb-99bb-3f359b222886.png)

2021-05-31 11:11 UTC, ValyaBro commented
вообщем нет, нам не нужны такие поля по бокам скриншота, я выше откомментила этот момент. Вариант совсем без полей тоже не ок, так скриншот будет сливаться с полем страницы, глазу будет сложно разделить текстовый блок и иллюстрацию. Важно придерживаться баланса: делать скриншот крупным и хорошо читаемым и при этом делать отбивку (фоном) от текстового поля статьи.

2021-05-31 13:16 UTC, igsekor commented
> tools/articles/network/images/1.png -> сейчас связи получились довольно хаотичными и трудно воспринимаемыми. Давай попробуем добавить больше привязки к сетке и сделать все стрелки или прямыми, или под углом 45 без изломов, или с изломом под 90 градусов? по моим ощущениям должна сработать компоновка всех сетевых устройств в одну вертикаль. + давай сделаем заголовок к схеме заголовком (Roboto Bold 64, в верхней части изображения, по центру)

@ValyaBro как раз смысл в том, чтобы подчеркнуть хаотичность связей. Важно, чтобы читатель понимал, что пакеты по сети могут пойти любым путём. Если выстроить в вертикаль, то мы покажем, что сетевые узлы — это слои. Тем более у нас получится один слой. Но это не так на практике. Какой-то пакет может проходить множество сетевых узлов, а какой-то всего несколько. Важно это подчеркнуть. Я понимаю, что мы выходим за рамки предусмотренной логике в дизайн-системе, но здесь пока ничего другого я не вижу, чтобы правильно сформировать у читателя абстракцию того, о чём он в этой статье читает. Что думаешь?

2021-06-01 22:01 UTC, nlopin commented on tools/articles/webserver/index.md
> +![Схема работы веб-сервера](images/1.png)
Я думаю вот эта схема ключевая. По сути, статьей мы хотим сказать, что веб-сервер умеет обрабатывать запросы и отправлять ответы. Остальное: сжатие, сертификаты — это детали и слои поверх.

Сейчас она выглядит так, будто есть один клиент и есть один запрос. Надо показать, что клиентов на самом деле много

2021-06-01 22:05 UTC, nlopin commented
> > tools/articles/network/images/1.png -> сейчас связи получились довольно хаотичными и трудно воспринимаемыми. Давай попробуем добавить больше привязки к сетке и сделать все стрелки или прямыми, или под углом 45 без изломов, или с изломом под 90 градусов? по моим ощущениям должна сработать компоновка всех сетевых устройств в одну вертикаль. + давай сделаем заголовок к схеме заголовком (Roboto Bold 64, в верхней части изображения, по центру)
> 
> @ValyaBro как раз смысл в том, чтобы подчеркнуть хаотичность связей. Важно, чтобы читатель понимал, что пакеты по сети могут пойти любым путём. Если выстроить в вертикаль, то мы покажем, что сетевые узлы — это слои. Тем более у нас получится один слой. Но это не так на практике. Какой-то пакет может проходить множество сетевых узлов, а какой-то всего несколько. Важно это подчеркнуть. Я понимаю, что мы выходим за рамки предусмотренной логики в дизайн-системе, но здесь пока ничего другого я не вижу, чтобы правильно подать читателю абстракцию того, о чём он в этой статье читает. Что думаешь?

Мне кажется, что если мы добавим анимацию к хаотичному набору узлов, то читателю будет понятно. Вот полетел первый пакет, он прошел через два узла, а вот полетел второй, он прошел через четыре, а третий вообще напрямую долетел

2021-06-02 10:00 UTC, igsekor commented on tools/articles/network/index.md
> +---
Мне показалось не очень, везде так пишут. @nlopin, я могу её добавить, если так будет понятнее...

2021-06-02 10:19 UTC, igsekor commented on tools/articles/webserver/index.md
> +Каждый заголовок в HTTP-сообщении представляется отдельной строкой с параметром и значением, разделёнными двоеточием. В заголовках содержится информация о домене, о сжатии, шифровании и формате данны
В [официальной документации](http://nginx.org/ru/docs/beginners_guide.html) так написано. Хотелось, чтобы терминология соответствовала. Я бы написал также "ключ": "значение", чтобы было похоже на объекты в JS.

2021-06-02 10:25 UTC, igsekor commented on tools/articles/webserver/index.md
> +![Схема работы веб-сервера](images/1.png)
Хорошо, давай перерисую

2021-06-02 10:27 UTC, igsekor commented on tools/articles/webserver/index.md
> +Во время отладки веб-приложений вы часто будете встречать коды ответов `200`, `404` и `500`. Коды ответов, которые начинаются на `2xx`, сервер возвращает, если запрос клиента был удачным. Запросы `4x
Можно вставить скриншоты неудачных запросов... Иначе придётся рассказывать, что такое curl... @nlopin , может и рассказать, полезно же будет?

2021-06-02 10:28 UTC, igsekor commented on tools/articles/webserver/index.md
> +В теле сообщения содержатся данные, которые требуется передать. Тело всегда отделяется от заголовков хотя бы одной пустой строкой. В теле, например, может передаваться [HTML-документ](/html/doka/html
Хорошо, вопрос и ответ.

2021-06-02 10:42 UTC, igsekor commented on tools/articles/webserver/index.md
> +После проверки сертификата браузер (клиент) и веб-сервер «договариваются» о ключах шифрования (открытом и закрытом). С помощью открытого ключа можно зашифровать данные пользователя на стороне клиента
Хотел предложить написать такую статью, даже несколько. Там есть, что рассказать. Завёл ишью: #734, #735, #736.

2021-06-02 10:44 UTC, igsekor commented on tools/articles/webserver/index.md
> +Подробнее о типах веб-приложений написано в статье «[Виды веб-приложений](/js/articles/web-app-types)».
Речь идёт об организации бэкенда (статические / динамические сайты на бэкенде). Переформатирую.

2021-06-02 10:44 UTC, igsekor commented on tools/articles/webserver/index.md
> +С помощью заголовков в HTTP-сообщениях можно осуществлять аутентификацию и авторизацию пользователей. Это можно реализовать и другим способом, если использовать куки браузера. В современных системах
Хорошо

2021-06-02 10:44 UTC, igsekor commented on tools/articles/webserver/index.md
> +Аутентификация пользователей возможна, если веб-серверу отдать учётные данные пользователя. При этом, веб-сервер проксирует эти данные приложению, в котором реализуется процедура аутентификации. В сл
Ок

2021-06-02 17:47 UTC, bespoyasov reviewed
Прочитал одну из 3 😅 
Завтра продолжу.

2021-06-02 17:47 UTC, bespoyasov commented on tools/articles/network/index.md
> +Применение HTTPS внесло ряд новых правил обработки данных, которые отныне не должны были передаваться в открытом виде, а должны были шифроваться. В протоколе HTTP используется TCP  в качестве транспо
Не уверен, надо ли, но после этого параграфа можно добавить коллаут со ссылкой на [«Безопасность веб-приложений и распространёные атаки»](https://new.y-doka.site/js/articles/web-security/) 🤔 

Будет ли уместно? @igsekor @nlopin

2021-06-02 17:47 UTC, bespoyasov commented on tools/articles/network/index.md
> +Браузер является одним из приложений на компьютере. Он использует определенный сетевой порт или несколько портов для отправки данных на сервер и получения данных, используя протоколы HTTP/HTTPS, UDP
```suggestion
Браузер — это одно из приложений на компьютере. Он использует определенный сетевой порт или несколько портов для отправки данных на сервер и получения данных, используя протоколы HTTP/HTTPS, UDP и другие. Также работает и почтовый клиент, только по другим протоколам — IMAP, POP3, SMTP. Мессенджеры типа ICQ, IRQ или Jabber тоже используют определённые протоколы для обмена сообщениями. Протоколы прикладного уровня лишь определяют формат передаваемых данных.
```

2021-06-02 17:47 UTC, bespoyasov commented on tools/articles/network/practice/igsekor.md
> +Если воспользоваться ключам `-s`, можно вывести статистику протоколам:
```suggestion
Если воспользоваться ключом `-s`, можно вывести статистику по протоколам:
```

2021-06-02 17:47 UTC, bespoyasov commented on tools/articles/network/practice/igsekor.md
> +Использование команды `man` подробно описано в статье «[Интерфейс командной строки](/tools/articles/cli)».
Сделаем пометку о [новых `ip` и `ss`](https://www.cyberciti.biz/faq/linux-ip-command-examples-usage-syntax/) и deprecation?

<img width="710" alt="«Screenshot» 2021-06-02 at 20 43 15" src="https://user-images.githubusercontent.com/9102374/120527720-579f9200-c3e3-11eb-8822-6e1bdf15f0ab.png">

2021-06-02 17:53 UTC, igsekor commented
> Прочитал одну из 3 😅
> Завтра продолжу.

Спасибо! :)

2021-06-02 18:10 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +Использование команды `man` подробно описано в статье «[Интерфейс командной строки](/tools/articles/cli)».
@bespoyasov я думал про это, но не решился. Хотя такую табличку можно было бы привести. Не хотел мозг забивать читателю, но наверное надо... Что думаешь, @nlopin?

2021-06-02 18:11 UTC, igsekor commented on tools/articles/network/index.md
> +Применение HTTPS внесло ряд новых правил обработки данных, которые отныне не должны были передаваться в открытом виде, а должны были шифроваться. В протоколе HTTP используется TCP  в качестве транспо
Мне кажется, да

2021-06-02 21:27 UTC, igsekor commented on tools/articles/webserver/index.md
> +Аутентификация пользователей возможна, если веб-серверу отдать учётные данные пользователя. При этом, веб-сервер проксирует эти данные приложению, в котором реализуется процедура аутентификации. В сл
Мне кажется, рисунок все же лишним будет. Вроде бы стало понятнее...

2021-06-02 22:24 UTC, nlopin commented on tools/articles/network/index.md
> +Применение HTTPS внесло ряд новых правил обработки данных, которые отныне не должны были передаваться в открытом виде, а должны были шифроваться. В протоколе HTTP используется TCP  в качестве транспо
да, давай добавим

2021-06-02 22:25 UTC, nlopin commented on tools/articles/network/practice/igsekor.md
> +Использование команды `man` подробно описано в статье «[Интерфейс командной строки](/tools/articles/cli)».
выглядит страшновато если чесн. Может под <details> уберем?

2021-06-06 11:22 UTC, ValyaBro reviewed
js/articles/architecture-mvc/images/app.png  -> картинку надо перерисовать целиком. сделайте, пожалуйста, тикет в ношен

2021-06-06 11:41 UTC, bespoyasov commented
> js/articles/architecture-mvc/images/app.png -> картинку надо перерисовать целиком. сделайте, пожалуйста, тикет в ношен

Вроде, уже есть:
https://www.notion.so/tbworkspace/MVC-be0a9ba1193d4678b2e225777f813775

2021-06-10 10:25 UTC, closed without merging