добавляет доку по cookie
Y-Doka/content pull request #726
Opened 2021-05-30 08:52 UTC by akellbl4

2021-05-31 18:34 UTC, nlopin commented
@akellbl4 кажется при переносе потерялись изменения, которые мы применяли [в старом репозитории](https://github.com/Y-Doka/y-doka.site/pull/725). Сможешь их принести?

2021-05-31 18:48 UTC, nlopin commented
Один коммит потерялся, перенёс сам

2021-05-31 18:59 UTC, nlopin requested changes
Последние штрихи

2021-05-31 18:59 UTC, nlopin commented on js/doka/cookie/index.md
> +Все куки хранятся в поле `document.cookie`. Это поле представляет из себя строку в формате `имя=значение`, где имя и значение разделяются знаком `; `. При этом взаимодействие с ней весьма необычное,
Попытался подробнее рассказать
```suggestion
Все куки хранятся в поле `document.cookie`. Это поле представляет из себя строку в формате `имя=значение`, где имя и значение разделяются знаком `; `. При этом взаимодействие с полем весьма необычное — если присвоить `document.cookie` новое значение, то оно не заменит полностью старую строку, а добавит или изменит значение по ключу.
```

2021-05-31 18:59 UTC, nlopin commented on js/doka/cookie/index.md
> +document.cookie = "sidebar=false";
давай сюда добавим, как будет выглядеть строка, если её прочитать

2021-05-31 18:59 UTC, nlopin commented on js/doka/cookie/index.md
> +Предположим, что до этого у нас не было установлено никаких кук. И при повторном присвоении куки с другим именем, мы получим два записанных значения.
надо еще рассказать, как происходит изменение значения по ключу, сейчас только в абзаце выше коротко про это говорим

2021-06-03 07:16 UTC, akellbl4 commented on js/doka/cookie/index.md
> +document.cookie = "sidebar=false";
я специально писал от записи к чтению, чтобы последовательно показать запись и ниже показать чтение.

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +::: callout 💡
```suggestion
::: callout 💡

```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +:::
```suggestion

:::
```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +::: callout 💡
```suggestion
::: callout 💡

```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +:::
```suggestion

:::
```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +::: callout 💡
```suggestion
::: callout 💡

```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +:::
```suggestion

:::
```

2021-06-04 10:03 UTC, bespoyasov commented on js/doka/cookie/index.md
> +Для получения значений, записанных в cookie, можно просто вывести содержимое `document.cookie`
```suggestion
Для получения значений, записанных в cookie, можно просто вывести содержимое `document.cookie`:
```

2021-06-04 20:09 UTC, akellbl4 commented
@bespoyasov спеллеру все равно не нравится картинка :)

2021-06-04 20:45 UTC, igsekor commented
> @bespoyasov спеллеру все равно не нравится картинка :)

Тесты смогут пройти, если сделать [так](https://github.com/Y-Doka/content/pull/750#issuecomment-854731278).

2021-06-05 09:33 UTC, bespoyasov commented
> спеллеру все равно не нравится картинка :)

Тут, вроде, в другом дело. 

Я там про Eleventy говорил, что он не превращает `::: callout` в коллаут, пока мы не добавим пустые строки между текстом и двоеточиями.

2021-06-05 09:34 UTC, bespoyasov approved these changes

2021-06-06 21:32 UTC, nlopin commented
> Я там про Eleventy говорил, что он не превращает `::: callout` в коллаут, пока мы не добавим пустые строки между текстом и двоеточиями.

У нас ещё не перенесен рендеринг калаутов на новый движок.

2021-06-06 21:41 UTC, nlopin approved these changes

2021-06-06 22:03 UTC, merged