Добавляет статью «Веб-сервер»
Y-Doka/content pull request #747
Opened 2021-06-03 08:49 UTC by igsekor

Статья связана с #341

2021-06-03 10:49 UTC, pepelsbey reviewed
«Настройка Nginx» это не практика, это отдельная статья.

2021-06-03 13:26 UTC, bespoyasov reviewed
В списке согласовал предложения друг с другом, а в остальным местах докинул пару идей.

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +2. Заголовки (Headers), которые описывают тело сообщения, параметры передачи и прочие сведения;
```suggestion
2. Заголовки (Headers) описывают тело сообщения, параметры передачи и прочие сведения;
```

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +1. Стартовая строка (Starting line), говорит нам, сообщение содержит запрос или ответ;
```suggestion
1. Стартовая строка (Starting line) говорит нам, запрос или ответ содержит сообщение;
```

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +3. Тело сообщения (Message Body) — данные.
```suggestion
3. Тело сообщения (Message Body) содержит данные.
```

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +Методы HTTP-запроса устанавливают назначение запроса. Среди наиболее используемых `GET`, `POST` и `OPTIONS`. Когда вы набираете адрес в адресной строке браузера и переходите по ссылке, обычно вы поль
Тут можно коллаут про [API](https://new.y-doka.site/js/articles/api/#kakie-api-byvayut) добавить, но я не уверен. Потому что REST и HTTP-глаголы — это всё-таки не одно и тоже 🤔 

Что думаешь об этом?

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +Версия протокола обязательно указывается в запросе, поскольку от неё зависит способ передачи данных и набор доступных методов.
А давай добавим сюда небольшую сноску с разницей между HTTP 1.1 и HTTP 2? 
(Можно рассказать, как разные протоколы сказываются на ощущении от сервиса для конечного пользователя.)

Но если это будет слишком много, то необязательно 🙃

2021-06-03 13:26 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +Во время отладки веб-приложений вы часто будете встречать коды ответов `200`, `404` и `500`. Коды ответов, которые начинаются на `2xx`, сервер возвращает, если запрос клиента был удачным. Запросы `4x
Сюда можно коллаут с [httpstatuses.com](https://httpstatuses.com) — постоянно забываю, какие статусы что значат 😅

2021-06-03 16:36 UTC, igsekor commented
> «Настройка Nginx» это не практика, это отдельная статья.

Например, можно было запустить и остановить веб-сервер. Это было бы практикой? Но это могут сделать и без статьи люди, первая же строчка любого руководства будет примерно об этом говорить.

@pepelsbey, а я ещё убрал уже написанный раздел «Настройка Apache» именно из-за объёма. Написать отдельные статьи недолго, но... Так что же такое раздел «Практика» и как он соотносится с разделом «В работе»?

2021-06-03 16:39 UTC, igsekor commented on tools/articles/webserver/index.md
> +Методы HTTP-запроса устанавливают назначение запроса. Среди наиболее используемых `GET`, `POST` и `OPTIONS`. Когда вы набираете адрес в адресной строке браузера и переходите по ссылке, обычно вы поль
Можно в формате «они используются тут», мне кажется, что будет действительно уместно.

2021-06-03 16:40 UTC, igsekor commented on tools/articles/webserver/index.md
> +Версия протокола обязательно указывается в запросе, поскольку от неё зависит способ передачи данных и набор доступных методов.
Предлагаю сделать отдельную статью. Там очень много материала.

Что думаешь, @nlopin?

2021-06-03 16:40 UTC, igsekor commented on tools/articles/webserver/index.md
> +Во время отладки веб-приложений вы часто будете встречать коды ответов `200`, `404` и `500`. Коды ответов, которые начинаются на `2xx`, сервер возвращает, если запрос клиента был удачным. Запросы `4x
Это верно! :)

2021-06-03 17:30 UTC, bespoyasov commented on tools/articles/webserver/index.md
> +Версия протокола обязательно указывается в запросе, поскольку от неё зависит способ передачи данных и набор доступных методов.
Или так, да ^_^

2021-06-03 18:52 UTC, pepelsbey commented
@igsekor практика — это советы из работы по мотивам статьи. Когда у тебя был опыт, который не укладывается в теорию. И ты от себя его пишешь. У тебя же и статья, и практика к ней в одном стиле — в стиле статьи.

Мы просто не сможем вывести это адекватно в интерфейсе. Так что тут очевидно две статьи и по объёму, и по жанру.

2021-06-03 19:38 UTC, igsekor commented
> @igsekor практика — это советы из работы по мотивам статьи. Когда у тебя был опыт, который не укладывается в теорию. И ты от себя его пишешь. У тебя же и статья, и практика к ней в одном стиле — в стиле статьи.
> 
> Мы просто не сможем вывести это адекватно в интерфейсе. Так что тут очевидно две статьи и по объёму, и по жанру.

Хорошо. Тогда после проверки разделю на две, подумаю насчет практики для всех трёх статей.

2021-06-04 09:48 UTC, bespoyasov reviewed
По содержанию 👍 

@nlopin, поглядишь-апрувнешь?

2021-06-05 09:48 UTC, bespoyasov reviewed
Предложил пару изменений: ссылку поправил, команду в терминале и слегка перефразировал последние абзацы.

2021-06-05 09:48 UTC, bespoyasov commented on tools/articles/webserver/practice/igsekor.md
> +Теперь в браузере вы можете видеть свой сайт по адресу [http://localhost:8080 ](http://localhost:8080 ).
```suggestion
Теперь в браузере вы можете видеть свой сайт по адресу [http://localhost:8080](http://localhost:8080).
```

2021-06-05 09:48 UTC, bespoyasov commented on tools/articles/webserver/practice/igsekor.md
> +npm install -global browser-sync
```suggestion
npm install --global browser-sync
```

2021-06-05 09:48 UTC, bespoyasov commented on tools/articles/webserver/practice/igsekor.md
> +Запуститься веб-сервер, и сайт будет доступен локально и в локальной сети. Если смартфон, планшет, ноутбук или десктоп находится в одной локальной сети, например, в WiFi-сети, то на всех устройствах
```suggestion
После этого запустится веб-сервер, и сайт будет доступен локально и в локальной сети. Если смартфон, планшет, ноутбук или десктоп находится в одной локальной сети, например, в WiFi-сети, то на всех устройствах сайт будет доступен. 

Более того, при взаимодействии пользователя с сайтом на одном из устройств, все действия будут немедленно воспроизводиться и на других устройствах. Например, если вы прокрутили страницу на смартфоне, она прокрутится и на других устройствах в сети. То же случится, если вы перейдёте на другую страницу сайта или будете взаимодействовать с формами. 

`browser-sync` удобно использовать и при разработке, и при тестировании проектов, потому что избавляет разработчиков от необходимости повторять рутинные действия вручную.
```

2021-06-06 07:47 UTC, bespoyasov approved these changes
🚀

2021-06-06 12:20 UTC, ValyaBro requested changes
- tools/articles/webserver/images/1.png 
отличный первая версия! Давай попробуем чуть вычистить её. Сейчас хочется сделать второстепенные блоки на стрелках одиноковой ширины, так они будут восприниматься сущностями одного вида и будут выглядеть аккуратнее. плюс хочется добавить между этими блоками больше воздуха, сейчас они немного слиплись. По ощущениям, если сделать между ними по вертикали около 5–6 px будет свободнее. Если увеличить расстояние между подписями стрелок по вертикали, может возникнуть сложность со стыковкой стрелок в блок «клиент», может быть спасёт ситуацию изменение его формы на круглую. И сейчас есть ощущение, что поля сверху и снизу довольно большие, хочется сделать их меньше.

2021-06-06 18:37 UTC, igsekor commented
> * tools/articles/webserver/images/1.png
>   отличный первая версия! Давай попробуем чуть вычистить её. Сейчас хочется сделать второстепенные блоки на стрелках одиноковой ширины, так они будут восприниматься сущностями одного вида и будут выглядеть аккуратнее. плюс хочется добавить между этими блоками больше воздуха, сейчас они немного слиплись. По ощущениям, если сделать между ними по вертикали около 5–6 px будет свободнее. Если увеличить расстояние между подписями стрелок по вертикали, может возникнуть сложность со стыковкой стрелок в блок «клиент», может быть спасёт ситуацию изменение его формы на круглую. И сейчас есть ощущение, что поля сверху и снизу довольно большие, хочется сделать их меньше.

Попробовал сделать лучше 😇

2021-06-07 09:20 UTC, pepelsbey requested changes
Надо переименовать папку в `web-server`, так будет по-английски. В примере ниже тоже есть написание без дефиса.

2021-06-07 10:03 UTC, igsekor commented
> Надо переименовать папку в `web-server`, так будет по-английски. В примере ниже тоже есть написание без дефиса.

Сделал 😇

2021-06-08 16:27 UTC, pepelsbey approved these changes

2021-06-10 05:11 UTC, nlopin commented
На картинке и текст, и многоточие 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/1469636/121468475-231b6f80-c9bb-11eb-9a4c-cc3cbf0dbad0.png">

2021-06-10 05:20 UTC, nlopin commented on tools/articles/web-server/index.md
> +Стартовая строка HTTP-ответа содержит:
классно, что для ответа есть список того, что должно быть. давай сделаем такой же для запроса?

Думаю, что он должен быть нумерованным, потому что порядок важен

2021-06-10 05:22 UTC, nlopin commented on tools/articles/web-server/index.md
> +Например, вы можете воспользоваться переводчиком таким образом:
строка кажется не отсюда

2021-06-10 05:23 UTC, nlopin commented on tools/articles/web-server/index.md
> +В теле сообщения содержатся данные, которые требуется передать. Тело всегда отделяется от заголовков хотя бы одной пустой строкой. В теле, например, может передаваться [HTML-документ](/html/doka/html
Давай еще докинем:
```suggestion
В теле сообщения содержатся данные, которые требуется передать. Тело всегда отделяется от заголовков хотя бы одной пустой строкой. В теле, например, может передаваться [HTML-документ](/html/doka/html) или [JSON](/js/doka/json/) с данными.
```

2021-06-10 05:25 UTC, nlopin commented on tools/articles/web-server/index.md
> +В последние годы браузеры стали поддерживать ещё два формата: [zopfli](https://ru.wikipedia.org/wiki/Zopfli) и [brotli](https://ru.wikipedia.org/wiki/Brotli). Наиболее перспективным и эффективным явл
Может так?
```suggestion
В последние годы браузеры стали поддерживать ещё два формата: [zopfli](https://ru.wikipedia.org/wiki/Zopfli) и [brotli](https://ru.wikipedia.org/wiki/Brotli). Наиболее перспективным и эффективным является brotli, он поддерживается всеми современными браузерами.
```

2021-06-10 05:32 UTC, nlopin commented on tools/articles/web-server/practice/igsekor.md
> +## Если надо больше
тут надо бы оставить имена продакшн серверов и ссылки на наши материалы по ним или сделать это маленьким дополнительным разделом?

2021-06-10 09:54 UTC, igsekor commented on tools/articles/web-server/index.md
> +Стартовая строка HTTP-ответа содержит:
Сделал! :)

2021-06-10 09:55 UTC, igsekor commented on tools/articles/web-server/index.md
> +Например, вы можете воспользоваться переводчиком таким образом:
Точно! Был другой пример сначала...

2021-06-10 10:03 UTC, igsekor commented
> На картинке и текст, и многоточие

Исправил.

2021-06-10 11:12 UTC, nlopin approved these changes

2021-06-10 14:45 UTC, ValyaBro approved these changes
картинка ок

2021-06-12 16:41 UTC, merged