Добавляет статью о веб-сервере Nginx
Y-Doka/content pull request #808
Opened 2021-06-04 19:46 UTC by igsekor

Эта статья первая из двух, которые соответствуют #316.

2021-06-05 09:41 UTC, bespoyasov reviewed
Докинул пару идей 🙂

2021-06-05 09:41 UTC, bespoyasov commented on tools/articles/webserver-nginx/index.md
> +Веб-сервер Nginx был разработан в 2004 году Игорем Сысоевым для работы со статическим контентом и оказался очень быстрым. Благодаря модульности, Nginx постоянно обрастал функциональностью, и сейчас м
А давай тут сошлёмся на статью о веб-сервере так же, как у тебя это сделано в [статье о докере](https://new.y-doka.site/tools/articles/docker-data-management/)?

2021-06-05 09:41 UTC, bespoyasov commented on tools/articles/webserver-nginx/index.md
> +```
Думаю, будет полезно указать в «комментарии» название файла и расширение, чтобы читателям не приходилось гуглить, как описываются конфиги для сервера на Ngnix.

2021-06-05 09:41 UTC, bespoyasov commented on tools/articles/webserver-nginx/index.md
> +        fastcgi_pass  localhost:9000;
Тут тоже лучше добавить пояснения, что делает каждая из строк. Не уверен, правда, где: прямо в коде их оставить или куда-то их вынести 🤔

2021-06-05 09:41 UTC, bespoyasov commented on tools/articles/webserver-nginx/index.md
> +Можно получить конфигурационный файл с помощью сервиса [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org). Попробовать сгенерировать разные конфигурации позволит разобраться с конк
🔥

2021-06-05 11:47 UTC, igsekor commented on tools/articles/webserver-nginx/index.md
> +Веб-сервер Nginx был разработан в 2004 году Игорем Сысоевым для работы со статическим контентом и оказался очень быстрым. Благодаря модульности, Nginx постоянно обрастал функциональностью, и сейчас м
Точно! :)

2021-06-05 13:31 UTC, igsekor commented on tools/articles/webserver-nginx/index.md
> +```
Сделал

2021-06-05 13:31 UTC, igsekor commented on tools/articles/webserver-nginx/index.md
> +        fastcgi_pass  localhost:9000;
Мне, кажется, что так :)

2021-06-06 07:45 UTC, bespoyasov reviewed
👍

2021-06-07 09:18 UTC, pepelsbey requested changes
- Я бы переименовал псевдоним: nginx-web-server (так будет по-английски)
- Объяснил бы про 4 пробела в конфигах: у нас стиль кода в примерах 2, а тут внезапно

2021-06-07 09:32 UTC, igsekor commented
> * Я бы переименовал псевдоним: nginx-web-server (так будет по-английски)

Точно!

> * Объяснил бы про 4 пробела в конфигах: у нас стиль кода в примерах 2, а тут внезапно

Давай я просто сделаю 2 пробела :)

> Очень круто, что теперь это отдельная статья со своей практикой :)

Полностью согласен! Хорошая была идея!

2021-06-07 09:40 UTC, pepelsbey approved these changes

2021-06-07 10:18 UTC, bespoyasov approved these changes

2021-06-09 21:59 UTC, nlopin approved these changes

2021-06-09 21:59 UTC, merged