Добавляет статью о трёхслойной архитектуре
Y-Doka/content pull request #817
Opened 2021-06-05 18:27 UTC by bespoyasov

2021-06-06 17:34 UTC, igsekor requested changes
Классная статья! 👍 Внёс лишь несколько предложений.

2021-06-06 17:34 UTC, igsekor commented on js/articles/clean-architecture/index.md
> +Типы, которые описывают структуры данных домена, называют доменными типами. В JavaScript есть механизмы для описания структур данных: можно использовать объекты, массивы и встроенные примитивы.
```suggestion
С данными в домене можно работать, используя _доменные типы_. Это простые и сложные структуры данных: объекты, массивы и встроенные примитивы. В JavaScript есть механизмы для описания таких структур данных.
```

Показалось сложновато. Может так? 😇

2021-06-06 17:34 UTC, igsekor commented on js/articles/clean-architecture/index.md
> +Как правило, это обработчики команд, которые содержат знание о том, что именно надо сделать, когда вызвана какая-то команда. Кроме этого слой содержит _интерфейсы_ портов и адаптеров.
```suggestion
Как правило, это обработчики команд, которые содержат знание о том, что именно надо сделать, когда вызвана какая-то команда. Кроме этого, слой содержит _интерфейсы_ портов и адаптеров.
```

2021-06-06 17:34 UTC, igsekor commented on js/articles/clean-architecture/index.md
> +Прикладной слой реализует собой [функциональную архитектуру](https://blog.ploeh.dk/2020/03/02/impureim-sandwich/), где получением и отправкой данных занимаются функции с сайд-эффектами, а преобразова
```suggestion
Прикладной слой реализует [функциональную архитектуру](https://blog.ploeh.dk/2020/03/02/impureim-sandwich/), где получением и отправкой данных занимаются функции с сайд-эффектами, а преобразованием данных занимаются чистые функции.
```

2021-06-06 17:34 UTC, igsekor commented on js/articles/clean-architecture/index.md
> +Иногда shared kernel и слои могут переходить друг в друга — это зависит от глубины проектирования. Если наш код изоморфный и запускается ещё и на сервере, то от глобальных объектов зависеть напрямую
Может пояснить, что значит «изоморфный»? 🙃 Что думаете?

2021-06-06 17:34 UTC, igsekor commented on js/articles/clean-architecture/index.md
> +- Трёхслойная архитектура требует времени на проектирование и реализацию.
```suggestion
- Трёхслойная архитектура требует больше времени на проектирование и реализацию.
```

2021-06-06 18:05 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +- по каким признакам модуль должен быть отнесён к одному из слоёв;
Да, точно! Спасибо 🚀

2021-06-06 18:06 UTC, bespoyasov commented
Спасибо! Обновил.

2021-06-06 18:13 UTC, igsekor approved these changes
Круто! 👍

2021-06-08 21:53 UTC, nlopin requested changes
Мне нравится читать про архитектуру, но не оставляет ощущение, что это синтетические конструкции, которые никто не делает. 

Можем ли мы дать ссылки на примеры реальных или игрушечных проектов, написанных в такой парадигме? Как, например, обработчики через адаптеры вешаются?

Еще классно бы сказать, что такую архитектуру называют луковой (onion architecture). Или это не она? чем тогда отличается?

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +- какие слои архитектура предполагает;
Сейчас есть правило [всегда заканчивать перечисления точкой](https://github.com/Y-Doka/content/blob/main/docs/typography.md#%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F-%D0%B8-%D0%BF%D1%83%D0%BD%D0%BA%D1%82%D1%83%D0%B0%D1%86%D0%B8%D1%8F)

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Трёхслойная архитектура подразумевает разделение кода, как это отмечено в названии, на 3 слоя:
```suggestion
Трёхслойная архитектура подразумевает разделение кода на 3 слоя:
```

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Обычно на схемах слои вкладывают друг в друга подобным образом:
```suggestion
На схемах слои обычно вкладывают друг в друга подобным образом:
```

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +![Схематичное выделение слоёв: в центре домен, вокруг него — прикладной слой, снаружи — порты и адаптеры](images/architecture.png)
в финальной схеме надо продублировать названия на русском

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Например, в интернет-магазине в домен могут попасть сущности пользователя, товара, корзины, заказа, а также код для обработки этих данных.
Мне не очень нравится, что тут мы говорим нечётко. Я понимаю, что домен зависит от приложения, но это слишком глубоко для начинающих. Давай напишем чётко, что будет доменом

С доменом всегда самая большая засада. Начинающим, да и не только, сложно понять, что это такое

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Удобнее всего для описания типов данных использовать TypeScript. В нём можно описать схему данных для какой-то сущности так:
Давай сошлёмся на https://y-doka.site/js/tools/static-types/

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Как правило, это обработчики команд, которые содержат знание о том, что именно надо сделать, когда вызвана какая-то команда. Кроме этого, слой содержит _интерфейсы_ портов и адаптеров.
Как-то сложно получилось. Что такое команда? dom event? Может так:

```suggestion
Обычно, это обработчики команд, которые выполняют пользовательский сценарий. Кроме этого, слой содержит _интерфейсы_ портов и адаптеров.
```

Тут не хватает примера какой-то конкретной команды

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Когда чистая функция преобразования данных помещена в «нечистый» контекст, функции с сайд-эффектами вызывают чистые функции и не наоборот.
я не сразу понял, что имеется ввиду. Зачем этот калаут? мы хотим сформулировать правило?

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Порт — это спецификация, как сторонний сервис _может_ общаться с нашим приложением, или как наше приложение _хочет_, чтобы с ним общались сторонние сервисы.
давай добавим примеры, а то у адаптера они есть, а здесь нет

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +В целом степень проработки и проектирования зависит от требований к приложению. Одно дело, когда у нас небольшой интернет-магазин, который работает только в браузере, и другое — когда у нас React-при
```suggestion
В целом, степень проработки и проектирования зависит от требований к приложению. Одно дело, когда у нас небольшой интернет-магазин, который работает только в браузере, и другое — когда у нас React-приложение, которое должно работать в браузере, рендериться на сервере и шарить код с React-Native проектом.
```

2021-06-08 21:53 UTC, nlopin commented on js/articles/clean-architecture/index.md
> +Адаптер должен позволить нам заменить внешний сервис на другой без изменения кода прикладного слоя. Поэтому сперва нам следует спроектировать интерфейс для порта или адаптера, и только потом писать р
Как-то резко статья обрывается. Может даадим ссылки на код реальных или игрушечных проектов, написанным с таким подходом?

2021-06-09 07:24 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +Адаптер должен позволить нам заменить внешний сервис на другой без изменения кода прикладного слоя. Поэтому сперва нам следует спроектировать интерфейс для порта или адаптера, и только потом писать р
Дал ссылку на https://github.com/bespoyasov/treees.

2021-06-09 07:25 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +Адаптер должен позволить нам заменить внешний сервис на другой без изменения кода прикладного слоя. Поэтому сперва нам следует спроектировать интерфейс для порта или адаптера, и только потом писать р
Через месяц поменяю её на другой пример 😃

2021-06-09 07:43 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +Порт — это спецификация, как сторонний сервис _может_ общаться с нашим приложением, или как наше приложение _хочет_, чтобы с ним общались сторонние сервисы.
Добавил.

2021-06-09 07:45 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +Когда чистая функция преобразования данных помещена в «нечистый» контекст, функции с сайд-эффектами вызывают чистые функции и не наоборот.
Переделал.

2021-06-09 08:07 UTC, bespoyasov commented on js/articles/clean-architecture/index.md
> +![Схематичное выделение слоёв: в центре домен, вокруг него — прикладной слой, снаружи — порты и адаптеры](images/architecture.png)
Обновил.

2021-06-09 08:07 UTC, bespoyasov commented
> Мне нравится читать про архитектуру, но не оставляет ощущение, что это синтетические конструкции, которые никто не делает.

Их во фронтенде почти никто и не делает 😃 

> Можем ли мы дать ссылки на примеры реальных или игрушечных проектов, написанных в такой парадигме? Как, например, обработчики через адаптеры вешаются?

Я не знаю примеров фронтендных опен-сорсных проектов, которые бы были так построены. Либо закрытый код, либо сделано по-другому.

Из игрушечных пока могу дать ссылку только на один — https://github.com/bespoyasov/treees.
Через месяц смогу дать ссылку на ещё один, там как раз будет «интернет-магазин».

2021-06-12 11:35 UTC, nlopin approved these changes

2021-06-12 11:36 UTC, merged