Element.innerText + Element.textContent
Y-Doka/content pull request #818
Opened 2021-06-06 16:51 UTC by Windrushfarer

Closes #742 & #743

2021-06-07 07:35 UTC, bespoyasov reviewed
Всё 👍 

Докинул идею для примеров.

2021-06-07 07:35 UTC, bespoyasov commented on js/doka/element-innertext/index.md
> +Свойство `Element.innerText` работает и как геттер и как сеттер: обращение к свойство вернёт текстовое содержимое элементов и его потомков, а установка нового значения изменит все текстовое содержимо
```suggestion
Свойство `Element.innerText` работает и как геттер, и как сеттер: обращение к свойству вернёт текстовое содержимое элементов и его потомков, а установка нового значения изменит все текстовое содержимое элемента.
```

2021-06-07 07:35 UTC, bespoyasov commented on js/doka/element-innertext/index.md
> +```
Может, кстати, добавить пример, в котором `innerText` будет возвращать текст элемента и его потомков? 

Типа:

```html
<main>
<h1>Заголовок</h1>
<p>Текст.</p>
</main>
```

```js
document.querySelector('main').innerText;
```

2021-06-07 07:35 UTC, bespoyasov commented on js/doka/element-innertext/index.md
> +::: callout ❗️
🚀

2021-06-07 20:06 UTC, Windrushfarer commented on js/doka/element-innertext/index.md
> +```
Докинул примеров ;)

2021-06-08 12:06 UTC, bespoyasov commented on js/doka/element-innertext/index.md
> +```
🔥

2021-06-09 22:10 UTC, nlopin commented
Стоит еще явно проговорить, что происходит, если я в каждый из них попробую записать валидный HTML

2021-06-09 22:18 UTC, nlopin requested changes
* стоит явно проговорить, что происходит, если я в каждый из них попробую записать валидный HTML 
* хочется пример, где мы читаем текст и видим, что он берется из потомков тоже
* говорим, что текст из скрытых узлов читается/не читается, но в примерах скрытых узлов нет

Мне не очень нравится, что доки пытаются объяснить себя, с помощью ссылки на другое свойство. Получается, чтобы понять его, мне нужно идти читать другую статью, а та статья ссылается на первую и мы в рекурсии. Лучше сказать, что делает свойство, а затем, что есть похожее свойство Х, которое отличается вот этим.

2021-06-10 16:04 UTC, Windrushfarer commented
> хочется пример, где мы читаем текст и видим, что он берется из потомков тоже
Они есть в обеих статьях. Или нужно в разделе пример это делать?

2021-06-10 16:24 UTC, Windrushfarer commented
@nlopin Должно стать лучше 👐  Спасибо за замечания

2021-06-12 16:28 UTC, nlopin commented
@Windrushfarer давай добавим «в работе»? Я бы там написал хотя бы о том, что нужно использовать эти методы для установки текстового значения, и ни в коем случае не использовать `innerHTML`, потому что небезопасно

2021-06-12 19:54 UTC, Windrushfarer commented
> @Windrushfarer давай добавим «в работе»? Я бы там написал хотя бы о том, что нужно использовать эти методы для установки текстового значения, и ни в коем случае не использовать `innerHTML`, потому что небезопасно

@nlopin по тексту это есть в разделе "Как понять" например, причем в обеих статьях, разве нужно дублировать? В самом `innerHTML` #905  про безопасность тоже сказано.

2021-06-12 20:47 UTC, nlopin commented
Ок, давай тогда так оставим

2021-06-12 20:49 UTC, nlopin approved these changes

2021-06-12 20:49 UTC, merged